/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Enumerates the account subtypes that the application wishes for the user to be able to select from. For more details refer to Plaid documentation on account filters.
*/
export class AccountFilter {
    /**
    * A list of account subtypes to be filtered.
    */
    'depository'?: Array<string>;
    /**
    * A list of account subtypes to be filtered.
    */
    'credit'?: Array<string>;
    /**
    * A list of account subtypes to be filtered.
    */
    'loan'?: Array<string>;
    /**
    * A list of account subtypes to be filtered.
    */
    'investment'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "depository",
            "baseName": "depository",
            "type": "Array<string>"
        },
        {
            "name": "credit",
            "baseName": "credit",
            "type": "Array<string>"
        },
        {
            "name": "loan",
            "baseName": "loan",
            "type": "Array<string>"
        },
        {
            "name": "investment",
            "baseName": "investment",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return AccountFilter.attributeTypeMap;
    }
}

