/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountProductAccessNullable } from './accountProductAccessNullable';

/**
* Allow or disallow product access by account. Unlisted (e.g. missing) accounts will be considered `new_accounts`.
*/
export class AccountAccess {
    /**
    * The unique account identifier for this account. This value must match that returned by the data access API for this account.
    */
    'uniqueId': string;
    /**
    * Allow the application to see this account (and associated details, including balance) in the list of accounts  If unset, defaults to `true`.
    */
    'authorized'?: boolean | null = true;
    'accountProductAccess'?: AccountProductAccessNullable | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uniqueId",
            "baseName": "unique_id",
            "type": "string"
        },
        {
            "name": "authorized",
            "baseName": "authorized",
            "type": "boolean"
        },
        {
            "name": "accountProductAccess",
            "baseName": "account_product_access",
            "type": "AccountProductAccessNullable"
        }    ];

    static getAttributeTypeMap() {
        return AccountAccess.attributeTypeMap;
    }
}

