/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* See the [Account type schema](https://plaid.com/docs/api/accounts/#account-type-schema) for a full listing of account types and corresponding subtypes.
*/
export enum AccountSubtype {
    _401a = <any> '401a',
    _401k = <any> '401k',
    _403B = <any> '403B',
    _457b = <any> '457b',
    _529 = <any> '529',
    Brokerage = <any> 'brokerage',
    CashIsa = <any> 'cash isa',
    EducationSavingsAccount = <any> 'education savings account',
    Ebt = <any> 'ebt',
    FixedAnnuity = <any> 'fixed annuity',
    Gic = <any> 'gic',
    HealthReimbursementArrangement = <any> 'health reimbursement arrangement',
    Hsa = <any> 'hsa',
    Isa = <any> 'isa',
    Ira = <any> 'ira',
    Lif = <any> 'lif',
    LifeInsurance = <any> 'life insurance',
    Lira = <any> 'lira',
    Lrif = <any> 'lrif',
    Lrsp = <any> 'lrsp',
    NonTaxableBrokerageAccount = <any> 'non-taxable brokerage account',
    Other = <any> 'other',
    OtherInsurance = <any> 'other insurance',
    OtherAnnuity = <any> 'other annuity',
    Prif = <any> 'prif',
    Rdsp = <any> 'rdsp',
    Resp = <any> 'resp',
    Rlif = <any> 'rlif',
    Rrif = <any> 'rrif',
    Pension = <any> 'pension',
    ProfitSharingPlan = <any> 'profit sharing plan',
    Retirement = <any> 'retirement',
    Roth = <any> 'roth',
    Roth401k = <any> 'roth 401k',
    Rrsp = <any> 'rrsp',
    SepIra = <any> 'sep ira',
    SimpleIra = <any> 'simple ira',
    Sipp = <any> 'sipp',
    StockPlan = <any> 'stock plan',
    ThriftSavingsPlan = <any> 'thrift savings plan',
    Tfsa = <any> 'tfsa',
    Trust = <any> 'trust',
    Ugma = <any> 'ugma',
    Utma = <any> 'utma',
    VariableAnnuity = <any> 'variable annuity',
    CreditCard = <any> 'credit card',
    Paypal = <any> 'paypal',
    Cd = <any> 'cd',
    Checking = <any> 'checking',
    Savings = <any> 'savings',
    MoneyMarket = <any> 'money market',
    Prepaid = <any> 'prepaid',
    Auto = <any> 'auto',
    Business = <any> 'business',
    Commercial = <any> 'commercial',
    Construction = <any> 'construction',
    Consumer = <any> 'consumer',
    HomeEquity = <any> 'home equity',
    Loan = <any> 'loan',
    Mortgage = <any> 'mortgage',
    Overdraft = <any> 'overdraft',
    LineOfCredit = <any> 'line of credit',
    Student = <any> 'student',
    CashManagement = <any> 'cash management',
    Keogh = <any> 'keogh',
    MutualFund = <any> 'mutual fund',
    Recurring = <any> 'recurring',
    Rewards = <any> 'rewards',
    SafeDeposit = <any> 'safe deposit',
    Sarsep = <any> 'sarsep',
    Payroll = <any> 'payroll',
    Null = <any> 'null'
}
