/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Address } from './address';
import { AddressData } from './addressData';

/**
* A physical mailing address.
*/
export class AddressNullable {
    'data': AddressData;
    /**
    * When `true`, identifies the address as the primary address on an account.
    */
    'primary'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "AddressData"
        },
        {
            "name": "primary",
            "baseName": "primary",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return AddressNullable.attributeTypeMap;
    }
}

