/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Metadata about the application
*/
export class Application {
    /**
    * This field will map to the application ID that is returned from /item/applications/list, or provided to the institution in an oauth redirect.
    */
    'applicationId': string;
    /**
    * The name of the application
    */
    'name': string;
    /**
    * The date this application was linked in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format in UTC.
    */
    'createdAt'?: string;
    /**
    * The date this application was granted production access at Plaid in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format in UTC.
    */
    'joinDate': string;
    /**
    * A URL that links to the application logo image.
    */
    'logoUrl': string | null;
    /**
    * The URL for the application\'s website
    */
    'applicationUrl': string | null;
    /**
    * A string provided by the connected app stating why they use their respective enabled products.
    */
    'reasonForAccess': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "applicationId",
            "baseName": "application_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "joinDate",
            "baseName": "join_date",
            "type": "string"
        },
        {
            "name": "logoUrl",
            "baseName": "logo_url",
            "type": "string"
        },
        {
            "name": "applicationUrl",
            "baseName": "application_url",
            "type": "string"
        },
        {
            "name": "reasonForAccess",
            "baseName": "reason_for_access",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Application.attributeTypeMap;
    }
}

