/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AssetReportTransactionAllOf {
    /**
    * The date on which the transaction took place, in IS0 8601 format.
    */
    'dateTransacted'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateTransacted",
            "baseName": "date_transacted",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AssetReportTransactionAllOf.attributeTypeMap;
    }
}

