/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AssetReportItem } from './assetReportItem';
import { AssetReportUser } from './assetReportUser';

/**
* An object representing an Asset Report
*/
export class AssetReport extends null<String, any> {
    /**
    * A unique ID identifying an Asset Report. Like all Plaid identifiers, this ID is case sensitive.
    */
    'assetReportId': string;
    /**
    * An identifier you determine and submit for the Asset Report.
    */
    'clientReportId': string | null;
    /**
    * The date and time when the Asset Report was created, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (e.g. \"2018-04-12T03:32:11Z\").
    */
    'dateGenerated': Date;
    /**
    * The duration of transaction history you requested
    */
    'daysRequested': number;
    'user': AssetReportUser;
    /**
    * Data returned by Plaid about each of the Items included in the Asset Report.
    */
    'items': Array<AssetReportItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "assetReportId",
            "baseName": "asset_report_id",
            "type": "string"
        },
        {
            "name": "clientReportId",
            "baseName": "client_report_id",
            "type": "string"
        },
        {
            "name": "dateGenerated",
            "baseName": "date_generated",
            "type": "Date"
        },
        {
            "name": "daysRequested",
            "baseName": "days_requested",
            "type": "number"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "AssetReportUser"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<AssetReportItem>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(AssetReport.attributeTypeMap);
    }
}

