/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AssetReport } from './assetReport';
import { Warning } from './warning';

/**
* AssetReportGetResponse defines the response schema for `/asset_report/get`
*/
export class AssetReportGetResponse extends null<String, any> {
    'report': AssetReport;
    /**
    * If the Asset Report generation was successful but identity information cannot be returned, this array will contain information about the errors causing identity information to be missing
    */
    'warnings': Array<Warning>;
    /**
    * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    */
    'requestId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "report",
            "baseName": "report",
            "type": "AssetReport"
        },
        {
            "name": "warnings",
            "baseName": "warnings",
            "type": "Array<Warning>"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(AssetReportGetResponse.attributeTypeMap);
    }
}

