/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountAssets } from './accountAssets';

/**
* A representation of an Item within an Asset Report.
*/
export class AssetReportItem extends null<String, any> {
    /**
    * The `item_id` of the Item associated with this webhook, warning, or error
    */
    'itemId': string;
    /**
    * The full financial institution name associated with the Item.
    */
    'institutionName': string;
    /**
    * The id of the financial institution associated with the Item.
    */
    'institutionId': string;
    /**
    * The date and time when this Item’s data was last retrieved from the financial institution, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
    */
    'dateLastUpdated': Date;
    /**
    * Data about each of the accounts open on the Item.
    */
    'accounts': Array<AccountAssets>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "itemId",
            "baseName": "item_id",
            "type": "string"
        },
        {
            "name": "institutionName",
            "baseName": "institution_name",
            "type": "string"
        },
        {
            "name": "institutionId",
            "baseName": "institution_id",
            "type": "string"
        },
        {
            "name": "dateLastUpdated",
            "baseName": "date_last_updated",
            "type": "Date"
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<AccountAssets>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(AssetReportItem.attributeTypeMap);
    }
}

