/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* AssetReportAuditCopyCreateResponse defines the response schema for `/asset_report/audit_copy/get`
*/
export class AssetReportAuditCopyCreateResponse extends null<String, any> {
    /**
    * A token that can be shared with a third party auditor to allow them to obtain access to the Asset Report. This token should be stored securely.
    */
    'auditCopyToken': string;
    /**
    * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    */
    'requestId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "auditCopyToken",
            "baseName": "audit_copy_token",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(AssetReportAuditCopyCreateResponse.attributeTypeMap);
    }
}

