/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NumbersACH } from './numbersACH';
import { NumbersBACS } from './numbersBACS';
import { NumbersEFT } from './numbersEFT';
import { NumbersInternational } from './numbersInternational';

/**
* An object containing identifying numbers used for making electronic transfers to and from the `accounts`. The identifying number type (ACH, EFT, IBAN, or BACS) used will depend on the country of the account. An account may have more than one number type. If a particular identifying number type is not used by any `accounts` for which data has been requested, the array for that type will be empty.
*/
export class AuthGetNumbers extends null<String, any> {
    /**
    * An array of ACH numbers identifying accounts.
    */
    'ach': Array<NumbersACH>;
    /**
    * An array of EFT numbers identifying accounts.
    */
    'eft': Array<NumbersEFT>;
    /**
    * An array of IBAN numbers identifying accounts.
    */
    'international': Array<NumbersInternational>;
    /**
    * An array of BACS numbers identifying accounts.
    */
    'bacs': Array<NumbersBACS>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ach",
            "baseName": "ach",
            "type": "Array<NumbersACH>"
        },
        {
            "name": "eft",
            "baseName": "eft",
            "type": "Array<NumbersEFT>"
        },
        {
            "name": "international",
            "baseName": "international",
            "type": "Array<NumbersInternational>"
        },
        {
            "name": "bacs",
            "baseName": "bacs",
            "type": "Array<NumbersBACS>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(AuthGetNumbers.attributeTypeMap);
    }
}

