/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ACHClass } from './aCHClass';
import { BankTransferNetwork } from './bankTransferNetwork';
import { BankTransferType } from './bankTransferType';
import { BankTransferUser } from './bankTransferUser';

/**
* Defines the request schema for `/bank_transfer/create`
*/
export class BankTransferCreateRequest {
    /**
    * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    */
    'clientId'?: string;
    /**
    * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    */
    'secret'?: string;
    /**
    * A random key provided by the client, per unique bank transfer. Maximum of 50 characters.  The API supports idempotency for safely retrying requests without accidentally performing the same operation twice. For example, if a request to create a bank transfer fails due to a network connection error, you can retry the request with the same idempotency key to guarantee that only a single bank transfer is created.
    */
    'idempotencyKey': string;
    /**
    * The Plaid `access_token` for the account that will be debited or credited.
    */
    'accessToken': string;
    /**
    * The Plaid `account_id` for the account that will be debited or credited.
    */
    'accountId': string;
    'type': BankTransferType;
    'network': BankTransferNetwork;
    /**
    * The amount of the bank transfer (decimal string with two digits of precision e.g. \"10.00\").
    */
    'amount': string;
    /**
    * The currency of the transfer amount – should be set to \"USD\".
    */
    'isoCurrencyCode': string;
    /**
    * The transfer description. Maximum of 10 characters.
    */
    'description': string;
    'achClass'?: ACHClass;
    'user': BankTransferUser;
    /**
    * An arbitrary string provided by the client for storage with the bank transfer. May be up to 100 characters.
    */
    'customTag'?: string | null;
    /**
    * The Metadata object is a mapping of client-provided string fields to any string value. The following limitations apply: - The JSON values must be Strings (no nested JSON objects allowed) - Only ASCII characters may be used - Maximum of 50 key/value pairs - Maximum key length of 40 characters - Maximum value length of 500 characters 
    */
    'metadata'?: { [key: string]: string; } | null;
    /**
    * Plaid’s unique identifier for the origination account for this transfer. If you have more than one origination account, this value must be specified. Otherwise, this field should be left blank.
    */
    'originationAccountId'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "idempotencyKey",
            "baseName": "idempotency_key",
            "type": "string"
        },
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BankTransferType"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "BankTransferNetwork"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "isoCurrencyCode",
            "baseName": "iso_currency_code",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "achClass",
            "baseName": "ach_class",
            "type": "ACHClass"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "BankTransferUser"
        },
        {
            "name": "customTag",
            "baseName": "custom_tag",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "originationAccountId",
            "baseName": "origination_account_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BankTransferCreateRequest.attributeTypeMap;
    }
}

