/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The legal name and other information for the account holder.
*/
export class BankTransferUser extends null<String, any> {
    /**
    * The account holder’s full legal name. If the transfer `ach_class` is `ccd`, this should be the business name of the account holder.
    */
    'legalName': string;
    /**
    * The account holder’s email.
    */
    'emailAddress'?: string | null;
    /**
    * The account holder\'s routing number. This field is only used in response data. Do not provide this field when making requests.
    */
    'routingNumber'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "legalName",
            "baseName": "legal_name",
            "type": "string"
        },
        {
            "name": "emailAddress",
            "baseName": "email_address",
            "type": "string"
        },
        {
            "name": "routingNumber",
            "baseName": "routing_number",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(BankTransferUser.attributeTypeMap);
    }
}

