/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RequestedScopes } from './requestedScopes';
import { ScopesNullable } from './scopesNullable';

/**
* Describes the connected application for a particular end user.
*/
export class ConnectedApplication {
    /**
    * This field will map to the application ID that is returned from /item/applications/list, or provided to the institution in an oauth redirect.
    */
    'applicationId': string;
    /**
    * The name of the application
    */
    'name': string;
    /**
    * A URL that links to the application logo image (will be deprecated in the future, please use logo_url).
    */
    'logo': string | null;
    /**
    * A URL that links to the application logo image.
    */
    'logoUrl': string | null;
    /**
    * The URL for the application\'s website
    */
    'applicationUrl': string | null;
    /**
    * A string provided by the connected app stating why they use their respective enabled products.
    */
    'reasonForAccess': string | null;
    /**
    * The date this application was linked in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format in UTC.
    */
    'createdAt': string;
    /**
    * The date this application was granted production access at Plaid in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format in UTC.
    */
    'joinDate': string;
    /**
    * (Deprecated) A list of enums representing the data collected and products enabled for this connected application.
    */
    'productDataTypes': Array<ConnectedApplication.ProductDataTypesEnum>;
    'scopes'?: ScopesNullable | null;
    'requestedScopes'?: RequestedScopes;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "applicationId",
            "baseName": "application_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "string"
        },
        {
            "name": "logoUrl",
            "baseName": "logo_url",
            "type": "string"
        },
        {
            "name": "applicationUrl",
            "baseName": "application_url",
            "type": "string"
        },
        {
            "name": "reasonForAccess",
            "baseName": "reason_for_access",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "joinDate",
            "baseName": "join_date",
            "type": "string"
        },
        {
            "name": "productDataTypes",
            "baseName": "product_data_types",
            "type": "Array<ConnectedApplication.ProductDataTypesEnum>"
        },
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "ScopesNullable"
        },
        {
            "name": "requestedScopes",
            "baseName": "requested_scopes",
            "type": "RequestedScopes"
        }    ];

    static getAttributeTypeMap() {
        return ConnectedApplication.attributeTypeMap;
    }
}

export namespace ConnectedApplication {
    export enum ProductDataTypesEnum {
        Balance = <any> 'ACCOUNT_BALANCE',
        UserInfo = <any> 'ACCOUNT_USER_INFO',
        Transactions = <any> 'ACCOUNT_TRANSACTIONS'
    }
}
