/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Fired when the status of a deposit switch request has changed.
*/
export class DepositSwitchStateUpdateWebhook {
    /**
    * `\"DEPOSIT_SWITCH\"`
    */
    'webhookType'?: string;
    /**
    * `\"SWITCH_STATE_UPDATE\"`
    */
    'webhookCode'?: string;
    /**
    *  The state, or status, of the deposit switch.  `initialized`: The deposit switch has been initialized with the user entering the information required to submit the deposit switch request.  `processing`: The deposit switch request has been submitted and is being processed.  `completed`: The user\'s employer has fulfilled and completed the deposit switch request.  `error`: There was an error processing the deposit switch request.  For more information, see the [Deposit Switch API reference](/docs/deposit-switch/reference#deposit_switchget).
    */
    'state'?: string;
    /**
    * The ID of the deposit switch.
    */
    'depositSwitchId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "webhookType",
            "baseName": "webhook_type",
            "type": "string"
        },
        {
            "name": "webhookCode",
            "baseName": "webhook_code",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "depositSwitchId",
            "baseName": "deposit_switch_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DepositSwitchStateUpdateWebhook.attributeTypeMap;
    }
}

