/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DepositSwitchCreateRequestOptions } from './depositSwitchCreateRequestOptions';
import { DepositSwitchTargetAccount } from './depositSwitchTargetAccount';
import { DepositSwitchTargetUser } from './depositSwitchTargetUser';

/**
* DepositSwitchAltCreateRequest defines the request schema for `/deposit_switch/alt/create`
*/
export class DepositSwitchAltCreateRequest {
    /**
    * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    */
    'clientId'?: string;
    /**
    * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    */
    'secret'?: string;
    'targetAccount': DepositSwitchTargetAccount;
    'targetUser': DepositSwitchTargetUser;
    'options'?: DepositSwitchCreateRequestOptions;
    /**
    * ISO-3166-1 alpha-2 country code standard.
    */
    'countryCode'?: DepositSwitchAltCreateRequest.CountryCodeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "targetAccount",
            "baseName": "target_account",
            "type": "DepositSwitchTargetAccount"
        },
        {
            "name": "targetUser",
            "baseName": "target_user",
            "type": "DepositSwitchTargetUser"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "DepositSwitchCreateRequestOptions"
        },
        {
            "name": "countryCode",
            "baseName": "country_code",
            "type": "DepositSwitchAltCreateRequest.CountryCodeEnum"
        }    ];

    static getAttributeTypeMap() {
        return DepositSwitchAltCreateRequest.attributeTypeMap;
    }
}

export namespace DepositSwitchAltCreateRequest {
    export enum CountryCodeEnum {
        Us = <any> 'US',
        Ca = <any> 'CA'
    }
}
