/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The deposit switch destination account
*/
export class DepositSwitchTargetAccount extends null<String, any> {
    /**
    * Account number for deposit switch destination
    */
    'accountNumber': string;
    /**
    * Routing number for deposit switch destination
    */
    'routingNumber': string;
    /**
    * The name of the deposit switch destination account, as it will be displayed to the end user in the Deposit Switch interface. It is not required to match the name used in online banking.
    */
    'accountName': string;
    /**
    * The account subtype of the account, either `checking` or `savings`.
    */
    'accountSubtype': DepositSwitchTargetAccount.AccountSubtypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountNumber",
            "baseName": "account_number",
            "type": "string"
        },
        {
            "name": "routingNumber",
            "baseName": "routing_number",
            "type": "string"
        },
        {
            "name": "accountName",
            "baseName": "account_name",
            "type": "string"
        },
        {
            "name": "accountSubtype",
            "baseName": "account_subtype",
            "type": "DepositSwitchTargetAccount.AccountSubtypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(DepositSwitchTargetAccount.attributeTypeMap);
    }
}

export namespace DepositSwitchTargetAccount {
    export enum AccountSubtypeEnum {
        Checking = <any> 'checking',
        Savings = <any> 'savings'
    }
}
