/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The type of document.  `DOCUMENT_TYPE_PAYSTUB`: A paystub.  `DOCUMENT_TYPE_BANK_STATEMENT`: A bank statement.  `DOCUMENT_TYPE_US_TAX_W2`: A W-2 wage and tax statement provided by a US employer reflecting wages earned by the employee.  `DOCUMENT_TYPE_US_MILITARY_ERAS`: An electronic Retirement Account Statement (eRAS) issued by the US military.  `DOCUMENT_TYPE_US_MILITARY_LES`: A Leave and Earnings Statement (LES) issued by the US military.  `DOCUMENT_TYPE_US_MILITARY_CLES`: A Civilian Leave and Earnings Statment (CLES) issued by the US military.  `DOCUMENT_TYPE_GIG`: Used to indicate that the income is related to gig work. Does not necessarily correspond to a specific document type.  `DOCUMENT_TYPE_NONE`: Used to indicate that there is no underlying document for the data.  `UNKNOWN`: Document type could not be determined.
*/
export enum DocType {
    Unknown = <any> 'UNKNOWN',
    DocumentTypePaystub = <any> 'DOCUMENT_TYPE_PAYSTUB',
    DocumentTypeBankStatement = <any> 'DOCUMENT_TYPE_BANK_STATEMENT',
    DocumentTypeUsTaxW2 = <any> 'DOCUMENT_TYPE_US_TAX_W2',
    DocumentTypeUsMilitaryEras = <any> 'DOCUMENT_TYPE_US_MILITARY_ERAS',
    DocumentTypeUsMilitaryLes = <any> 'DOCUMENT_TYPE_US_MILITARY_LES',
    DocumentTypeUsMilitaryCles = <any> 'DOCUMENT_TYPE_US_MILITARY_CLES',
    DocumentTypeGig = <any> 'DOCUMENT_TYPE_GIG',
    DocumentTypeNone = <any> 'DOCUMENT_TYPE_NONE'
}
