/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DocType } from './docType';

/**
* An object representing metadata from the end user\'s uploaded document.
*/
export class DocumentMetadata extends null<String, any> {
    /**
    * The name of the document.
    */
    'name'?: string;
    /**
    * The processing status of the document.
    */
    'status'?: string;
    /**
    * An identifier of the document that is also present in the paystub response.
    */
    'docId'?: string;
    'docType'?: DocType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "docId",
            "baseName": "doc_id",
            "type": "string"
        },
        {
            "name": "docType",
            "baseName": "doc_type",
            "type": "DocType"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(DocumentMetadata.attributeTypeMap);
    }
}

