/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EarningsBreakdown } from './earningsBreakdown';
import { EarningsTotal } from './earningsTotal';

/**
* An object representing both a breakdown of earnings on a paystub and the total earnings.
*/
export class Earnings extends null<String, any> {
    'subtotals'?: Array<EarningsTotal>;
    'totals'?: Array<EarningsTotal>;
    'breakdown'?: Array<EarningsBreakdown>;
    'total'?: EarningsTotal;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subtotals",
            "baseName": "subtotals",
            "type": "Array<EarningsTotal>"
        },
        {
            "name": "totals",
            "baseName": "totals",
            "type": "Array<EarningsTotal>"
        },
        {
            "name": "breakdown",
            "baseName": "breakdown",
            "type": "Array<EarningsBreakdown>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "EarningsTotal"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Earnings.attributeTypeMap);
    }
}

