/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An object representing an email address
*/
export class Email extends null<String, any> {
    /**
    * The email address.
    */
    'data': string;
    /**
    * When `true`, identifies the email address as the primary email on an account.
    */
    'primary': boolean;
    /**
    * The type of email account as described by the financial institution.
    */
    'type': Email.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "string"
        },
        {
            "name": "primary",
            "baseName": "primary",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Email.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Email.attributeTypeMap);
    }
}

export namespace Email {
    export enum TypeEnum {
        Primary = <any> 'primary',
        Secondary = <any> 'secondary',
        Other = <any> 'other'
    }
}
