/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Pay } from './pay';

/**
* An object representing employment details found on a paystub.
*/
export class EmploymentDetails extends null<String, any> {
    'annualSalary'?: Pay;
    /**
    * Date on which the employee was hired, in the YYYY-MM-DD format.
    */
    'hireDate'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "annualSalary",
            "baseName": "annual_salary",
            "type": "Pay"
        },
        {
            "name": "hireDate",
            "baseName": "hire_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(EmploymentDetails.attributeTypeMap);
    }
}

