/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EmployerVerification } from './employerVerification';
import { EmploymentVerificationStatus } from './employmentVerificationStatus';
import { PlatformIds } from './platformIds';

/**
* An object containing proof of employment data for an individual
*/
export class EmploymentVerification extends null<String, any> {
    'status'?: EmploymentVerificationStatus | null;
    /**
    * Start of employment in ISO 8601 format (YYYY-MM-DD).
    */
    'startDate'?: string | null;
    /**
    * End of employment, if applicable. Provided in ISO 8601 format (YYY-MM-DD).
    */
    'endDate'?: string | null;
    'employer'?: EmployerVerification;
    /**
    * Current title of employee.
    */
    'title'?: string | null;
    'platformIds'?: PlatformIds;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "EmploymentVerificationStatus"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string"
        },
        {
            "name": "employer",
            "baseName": "employer",
            "type": "EmployerVerification"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "platformIds",
            "baseName": "platform_ids",
            "type": "PlatformIds"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(EmploymentVerification.attributeTypeMap);
    }
}

