/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddressDataNullable } from './addressDataNullable';

/**
* Data about the employer.
*/
export class Employer extends null<String, any> {
    /**
    * Plaid\'s unique identifier for the employer.
    */
    'employerId': string;
    /**
    * The name of the employer
    */
    'name': string;
    'address': AddressDataNullable | null;
    /**
    * A number from 0 to 1 indicating Plaid\'s level of confidence in the pairing between the employer and the institution (not yet implemented).
    */
    'confidenceScore': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "employerId",
            "baseName": "employer_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "AddressDataNullable"
        },
        {
            "name": "confidenceScore",
            "baseName": "confidence_score",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Employer.attributeTypeMap);
    }
}

