/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SecurityOverride } from './securityOverride';

/**
* Specify the holdings on the account.
*/
export class HoldingsOverride {
    /**
    * The last price given by the institution for this security
    */
    'institutionPrice': number;
    /**
    * The date at which `institution_price` was current. Must be formatted as an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) date.
    */
    'institutionPriceAsOf'?: string;
    /**
    * The average original value of the holding. Multiple cost basis values for the same security purchased at different prices are not supported.
    */
    'costBasis'?: number;
    /**
    * The total quantity of the asset held, as reported by the financial institution.
    */
    'quantity': number;
    /**
    * Either a valid `iso_currency_code` or `unofficial_currency_code`
    */
    'currency': string;
    'security': SecurityOverride;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "institutionPrice",
            "baseName": "institution_price",
            "type": "number"
        },
        {
            "name": "institutionPriceAsOf",
            "baseName": "institution_price_as_of",
            "type": "string"
        },
        {
            "name": "costBasis",
            "baseName": "cost_basis",
            "type": "number"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "security",
            "baseName": "security",
            "type": "SecurityOverride"
        }    ];

    static getAttributeTypeMap() {
        return HoldingsOverride.attributeTypeMap;
    }
}

