/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An update on the health incident
*/
export class IncidentUpdate extends null<String, any> {
    /**
    * The content of the update.
    */
    'description'?: string;
    /**
    * The status of the incident.
    */
    'status'?: IncidentUpdate.StatusEnum;
    /**
    * The date when the update was published, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format, e.g. `\"2020-10-30T15:26:48Z\"`.
    */
    'updatedDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "IncidentUpdate.StatusEnum"
        },
        {
            "name": "updatedDate",
            "baseName": "updated_date",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(IncidentUpdate.attributeTypeMap);
    }
}

export namespace IncidentUpdate {
    export enum StatusEnum {
        Investigating = <any> 'INVESTIGATING',
        Identified = <any> 'IDENTIFIED',
        Scheduled = <any> 'SCHEDULED',
        Resolved = <any> 'RESOLVED',
        Unknown = <any> 'UNKNOWN'
    }
}
