/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaystubOverride } from './paystubOverride';

/**
* Specify payroll data on the account.
*/
export class IncomeOverride {
    /**
    * A list of paystubs associated with the account.
    */
    'paystubs'?: Array<PaystubOverride>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paystubs",
            "baseName": "paystubs",
            "type": "Array<PaystubOverride>"
        }    ];

    static getAttributeTypeMap() {
        return IncomeOverride.attributeTypeMap;
    }
}

