/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IncomeVerificationPrecheckConfidence } from './incomeVerificationPrecheckConfidence';

/**
* IncomeVerificationPrecheckResponse defines the response schema for `/income/verification/precheck`.
*/
export class IncomeVerificationPrecheckResponse extends null<String, any> {
    /**
    * ID of the precheck. Provide this value when calling `/link/token/create` in order to optimize Link conversion.
    */
    'precheckId': string;
    /**
    * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    */
    'requestId': string;
    'confidence': IncomeVerificationPrecheckConfidence;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "precheckId",
            "baseName": "precheck_id",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        },
        {
            "name": "confidence",
            "baseName": "confidence",
            "type": "IncomeVerificationPrecheckConfidence"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(IncomeVerificationPrecheckResponse.attributeTypeMap);
    }
}

