/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SignalAddressData } from './signalAddressData';

/**
* Information about the user whose eligibility is being evaluated.
*/
export class IncomeVerificationPrecheckUser {
    /**
    * The user\'s first name
    */
    'firstName'?: string | null;
    /**
    * The user\'s last name
    */
    'lastName'?: string | null;
    /**
    * The user\'s email address
    */
    'emailAddress'?: string | null;
    'homeAddress'?: SignalAddressData | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string"
        },
        {
            "name": "emailAddress",
            "baseName": "email_address",
            "type": "string"
        },
        {
            "name": "homeAddress",
            "baseName": "home_address",
            "type": "SignalAddressData"
        }    ];

    static getAttributeTypeMap() {
        return IncomeVerificationPrecheckUser.attributeTypeMap;
    }
}

