/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IncomeVerificationPrecheckEmployer } from './incomeVerificationPrecheckEmployer';
import { IncomeVerificationPrecheckMilitaryInfo } from './incomeVerificationPrecheckMilitaryInfo';
import { IncomeVerificationPrecheckUser } from './incomeVerificationPrecheckUser';

/**
* IncomeVerificationPrecheckRequest defines the request schema for `/income/verification/precheck`
*/
export class IncomeVerificationPrecheckRequest {
    /**
    * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    */
    'clientId'?: string;
    /**
    * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    */
    'secret'?: string;
    'user'?: IncomeVerificationPrecheckUser | null;
    'employer'?: IncomeVerificationPrecheckEmployer | null;
    'transactionsAccessToken'?: string | null;
    /**
    * An array of access tokens corresponding to Items belonging to the user whose eligibility is being checked. Note that if the Items specified here are not already initialized with `transactions`, providing them in this field will cause these Items to be initialized with (and billed for) the Transactions product.
    */
    'transactionsAccessTokens'?: Array<string>;
    'usMilitaryInfo'?: IncomeVerificationPrecheckMilitaryInfo | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "IncomeVerificationPrecheckUser"
        },
        {
            "name": "employer",
            "baseName": "employer",
            "type": "IncomeVerificationPrecheckEmployer"
        },
        {
            "name": "transactionsAccessToken",
            "baseName": "transactions_access_token",
            "type": "string"
        },
        {
            "name": "transactionsAccessTokens",
            "baseName": "transactions_access_tokens",
            "type": "Array<string>"
        },
        {
            "name": "usMilitaryInfo",
            "baseName": "us_military_info",
            "type": "IncomeVerificationPrecheckMilitaryInfo"
        }    ];

    static getAttributeTypeMap() {
        return IncomeVerificationPrecheckRequest.attributeTypeMap;
    }
}

