/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* IncomeVerificationDocumentsDownloadRequest defines the request schema for `/income/verification/documents/download`.
*/
export class IncomeVerificationDocumentsDownloadRequest {
    /**
    * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    */
    'clientId'?: string;
    /**
    * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    */
    'secret'?: string;
    /**
    * The ID of the verification.
    */
    'incomeVerificationId'?: string | null;
    /**
    * The access token associated with the Item data is being requested for.
    */
    'accessToken'?: string | null;
    /**
    * The document ID to download. If passed, a single document will be returned in the resulting zip file, rather than all document
    */
    'documentId'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "incomeVerificationId",
            "baseName": "income_verification_id",
            "type": "string"
        },
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "document_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IncomeVerificationDocumentsDownloadRequest.attributeTypeMap;
    }
}

