/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Fired when an Item\'s initial transaction pull is completed. Once this webhook has been fired, transaction data for the most recent 30 days can be fetched for the Item. If [Account Select v2](https://plaid.com/docs/link/customization/#account-select) is enabled, this webhook will also be fired if account selections for the Item are updated, with `new_transactions` set to the number of net new transactions pulled after the account selection update.
*/
export class InitialUpdateWebhook extends null<String, any> {
    /**
    * `TRANSACTIONS`
    */
    'webhookType': string;
    /**
    * `INITIAL_UPDATE`
    */
    'webhookCode': string;
    /**
    * The error code associated with the webhook.
    */
    'error'?: string | null;
    /**
    * The number of new, unfetched transactions available.
    */
    'newTransactions': number;
    /**
    * The `item_id` of the Item associated with this webhook, warning, or error
    */
    'itemId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "webhookType",
            "baseName": "webhook_type",
            "type": "string"
        },
        {
            "name": "webhookCode",
            "baseName": "webhook_code",
            "type": "string"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "newTransactions",
            "baseName": "new_transactions",
            "type": "number"
        },
        {
            "name": "itemId",
            "baseName": "item_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(InitialUpdateWebhook.attributeTypeMap);
    }
}

