/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountSubtype } from './accountSubtype';

/**
* An account filter to apply to institutions search requests
*/
export class InstitutionsSearchAccountFilter extends null<String, any> {
    'loan'?: Array<AccountSubtype>;
    'depository'?: Array<AccountSubtype>;
    'credit'?: Array<AccountSubtype>;
    'investment'?: Array<AccountSubtype>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "loan",
            "baseName": "loan",
            "type": "Array<AccountSubtype>"
        },
        {
            "name": "depository",
            "baseName": "depository",
            "type": "Array<AccountSubtype>"
        },
        {
            "name": "credit",
            "baseName": "credit",
            "type": "Array<AccountSubtype>"
        },
        {
            "name": "investment",
            "baseName": "investment",
            "type": "Array<AccountSubtype>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(InstitutionsSearchAccountFilter.attributeTypeMap);
    }
}

