/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InstitutionsSearchPaymentInitiationOptions } from './institutionsSearchPaymentInitiationOptions';

/**
* An optional object to filter `/institutions/search` results.
*/
export class InstitutionsSearchRequestOptions {
    /**
    * Limit results to institutions with or without OAuth login flows.
    */
    'oauth'?: boolean | null;
    /**
    * When true, return the institution\'s homepage URL, logo and primary brand color.
    */
    'includeOptionalMetadata'?: boolean;
    /**
    * When `true`, returns metadata related to the Auth product indicating which auth methods are supported.
    */
    'includeAuthMetadata'?: boolean | null = false;
    /**
    * When `true`, returns metadata related to the Payment Initiation product indicating which payment configurations are supported.
    */
    'includePaymentInitiationMetadata'?: boolean | null = false;
    'paymentInitiation'?: InstitutionsSearchPaymentInitiationOptions | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "oauth",
            "baseName": "oauth",
            "type": "boolean"
        },
        {
            "name": "includeOptionalMetadata",
            "baseName": "include_optional_metadata",
            "type": "boolean"
        },
        {
            "name": "includeAuthMetadata",
            "baseName": "include_auth_metadata",
            "type": "boolean"
        },
        {
            "name": "includePaymentInitiationMetadata",
            "baseName": "include_payment_initiation_metadata",
            "type": "boolean"
        },
        {
            "name": "paymentInitiation",
            "baseName": "payment_initiation",
            "type": "InstitutionsSearchPaymentInitiationOptions"
        }    ];

    static getAttributeTypeMap() {
        return InstitutionsSearchRequestOptions.attributeTypeMap;
    }
}

