/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Valid account subtypes for investment accounts. For a list containing descriptions of each subtype, see [Account schemas](https://plaid.com/docs/api/accounts/#StandaloneAccountType-investment).
*/
export enum InvestmentAccountSubtype {
    _529 = <any> '529',
    _401a = <any> '401a',
    _401k = <any> '401k',
    _403B = <any> '403B',
    _457b = <any> '457b',
    Brokerage = <any> 'brokerage',
    CashIsa = <any> 'cash isa',
    EducationSavingsAccount = <any> 'education savings account',
    FixedAnnuity = <any> 'fixed annuity',
    Gic = <any> 'gic',
    HealthReimbursementArrangement = <any> 'health reimbursement arrangement',
    Hsa = <any> 'hsa',
    Ira = <any> 'ira',
    Isa = <any> 'isa',
    Keogh = <any> 'keogh',
    Lif = <any> 'lif',
    LifeInsurance = <any> 'life insurance',
    Lira = <any> 'lira',
    Lrif = <any> 'lrif',
    Lrsp = <any> 'lrsp',
    MutualFund = <any> 'mutual fund',
    NonTaxableBrokerageAccount = <any> 'non-taxable brokerage account',
    Other = <any> 'other',
    OtherAnnuity = <any> 'other annuity',
    OtherInsurance = <any> 'other insurance',
    Person = <any> 'person',
    Prif = <any> 'prif',
    ProfitSharingPlan = <any> 'profit sharing plan',
    Qshr = <any> 'qshr',
    Rdsp = <any> 'rdsp',
    Resp = <any> 'resp',
    Retirement = <any> 'retirement',
    Rlif = <any> 'rlif',
    Roth = <any> 'roth',
    Roth401k = <any> 'roth 401k',
    Rrif = <any> 'rrif',
    Rrsp = <any> 'rrsp',
    Sarsep = <any> 'sarsep',
    SepIra = <any> 'sep ira',
    SimpleIra = <any> 'simple ira',
    Sipp = <any> 'sipp',
    StockPlan = <any> 'stock plan',
    Tfsa = <any> 'tfsa',
    Trust = <any> 'trust',
    Ugma = <any> 'ugma',
    Utma = <any> 'utma',
    VariableAnnuity = <any> 'variable annuity',
    All = <any> 'all'
}
