/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InvestmentsTransactionsGetRequestOptions } from './investmentsTransactionsGetRequestOptions';

/**
* InvestmentsTransactionsGetRequest defines the request schema for `/investments/transactions/get`
*/
export class InvestmentsTransactionsGetRequest {
    /**
    * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    */
    'clientId'?: string;
    /**
    * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    */
    'secret'?: string;
    /**
    * The access token associated with the Item data is being requested for.
    */
    'accessToken': string;
    /**
    * The earliest date for which to fetch transaction history. Dates should be formatted as YYYY-MM-DD.
    */
    'startDate': string;
    /**
    * The most recent date for which to fetch transaction history. Dates should be formatted as YYYY-MM-DD.
    */
    'endDate': string;
    'options'?: InvestmentsTransactionsGetRequestOptions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "InvestmentsTransactionsGetRequestOptions"
        }    ];

    static getAttributeTypeMap() {
        return InvestmentsTransactionsGetRequest.attributeTypeMap;
    }
}

