/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SecurityOverride } from './securityOverride';

/**
* Specify the list of investments transactions on the account.
*/
export class InvestmentsTransactionsOverride {
    /**
    * Posting date for the transaction. Must be formatted as an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) date.
    */
    'date': string;
    /**
    * The institution\'s description of the transaction.
    */
    'name': string;
    /**
    * The number of units of the security involved in this transaction. Must be positive if the type is a buy and negative if the type is a sell.
    */
    'quantity': number;
    /**
    * The price of the security at which this transaction occurred.
    */
    'price': number;
    /**
    * The combined value of all fees applied to this transaction.
    */
    'fees'?: number;
    /**
    * The type of the investment transaction. Possible values are: `buy`: Buying an investment `sell`: Selling an investment `cash`: Activity that modifies a cash position `fee`: A fee on the account `transfer`: Activity that modifies a position, but not through buy/sell activity e.g. options exercise, portfolio transfer
    */
    'type': string;
    /**
    * Either a valid `iso_currency_code` or `unofficial_currency_code`
    */
    'currency': string;
    'security'?: SecurityOverride;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "security",
            "baseName": "security",
            "type": "SecurityOverride"
        }    ];

    static getAttributeTypeMap() {
        return InvestmentsTransactionsOverride.attributeTypeMap;
    }
}

