/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PlaidError } from './plaidError';

/**
* Fired when new or canceled transactions have been detected on an investment account.
*/
export class InvestmentsDefaultUpdateWebhook extends null<String, any> {
    /**
    * `INVESTMENTS_TRANSACTIONS`
    */
    'webhookType': string;
    /**
    * `DEFAULT_UPDATE`
    */
    'webhookCode': string;
    /**
    * The `item_id` of the Item associated with this webhook, warning, or error
    */
    'itemId': string;
    'error'?: PlaidError;
    /**
    * The number of new transactions reported since the last time this webhook was fired.
    */
    'newInvestmentsTransactions': number;
    /**
    * The number of canceled transactions reported since the last time this webhook was fired.
    */
    'canceledInvestmentsTransactions': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "webhookType",
            "baseName": "webhook_type",
            "type": "string"
        },
        {
            "name": "webhookCode",
            "baseName": "webhook_code",
            "type": "string"
        },
        {
            "name": "itemId",
            "baseName": "item_id",
            "type": "string"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "PlaidError"
        },
        {
            "name": "newInvestmentsTransactions",
            "baseName": "new_investments_transactions",
            "type": "number"
        },
        {
            "name": "canceledInvestmentsTransactions",
            "baseName": "canceled_investments_transactions",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(InvestmentsDefaultUpdateWebhook.attributeTypeMap);
    }
}

