/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountBase } from './accountBase';
import { InvestmentTransaction } from './investmentTransaction';
import { Item } from './item';
import { Security } from './security';

/**
* InvestmentsTransactionsGetResponse defines the response schema for `/investments/transactions/get`
*/
export class InvestmentsTransactionsGetResponse extends null<String, any> {
    'item': Item;
    /**
    * The accounts for which transaction history is being fetched.
    */
    'accounts': Array<AccountBase>;
    /**
    * All securities for which there is a corresponding transaction being fetched.
    */
    'securities': Array<Security>;
    /**
    * The transactions being fetched
    */
    'investmentTransactions': Array<InvestmentTransaction>;
    /**
    * The total number of transactions available within the date range specified. If `total_investment_transactions` is larger than the size of the `transactions` array, more transactions are available and can be fetched via manipulating the `offset` parameter.\'
    */
    'totalInvestmentTransactions': number;
    /**
    * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    */
    'requestId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "item",
            "baseName": "item",
            "type": "Item"
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<AccountBase>"
        },
        {
            "name": "securities",
            "baseName": "securities",
            "type": "Array<Security>"
        },
        {
            "name": "investmentTransactions",
            "baseName": "investment_transactions",
            "type": "Array<InvestmentTransaction>"
        },
        {
            "name": "totalInvestmentTransactions",
            "baseName": "total_investment_transactions",
            "type": "number"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(InvestmentsTransactionsGetResponse.attributeTypeMap);
    }
}

