/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Object of user ID and auth token pair, permitting Plaid to aggregate a user’s accounts
*/
export class ItemImportRequestUserAuth {
    /**
    * Opaque user identifier
    */
    'userId': string;
    /**
    * Authorization token Plaid will use to aggregate this user’s accounts
    */
    'authToken': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string"
        },
        {
            "name": "authToken",
            "baseName": "auth_token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ItemImportRequestUserAuth.attributeTypeMap;
    }
}

