/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* User authentication parameters, for clients making a request without an `access_token`. This is only allowed for select clients and will not be supported in the future. Most clients should call /item/import to obtain an access token before making a request.
*/
export class ItemApplicationListUserAuth {
    /**
    * Account username.
    */
    'userId'?: string | null;
    /**
    * Account username hashed by FI.
    */
    'fiUsernameHash'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string"
        },
        {
            "name": "fiUsernameHash",
            "baseName": "fi_username_hash",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ItemApplicationListUserAuth.attributeTypeMap;
    }
}

