/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ItemStatus } from './itemStatus';
import { ItemStatusInvestments } from './itemStatusInvestments';
import { ItemStatusLastWebhook } from './itemStatusLastWebhook';
import { ItemStatusTransactions } from './itemStatusTransactions';

/**
* Information about the last successful and failed transactions update for the Item.
*/
export class ItemStatusNullable {
    'investments'?: ItemStatusInvestments | null;
    'transactions'?: ItemStatusTransactions | null;
    'lastWebhook'?: ItemStatusLastWebhook | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "investments",
            "baseName": "investments",
            "type": "ItemStatusInvestments"
        },
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "ItemStatusTransactions"
        },
        {
            "name": "lastWebhook",
            "baseName": "last_webhook",
            "type": "ItemStatusLastWebhook"
        }    ];

    static getAttributeTypeMap() {
        return ItemStatusNullable.attributeTypeMap;
    }
}

