/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An optional object to configure `/item/import` request.
*/
export class ItemImportRequestOptions {
    /**
    * Specifies a webhook URL to associate with an Item. Plaid fires a webhook if credentials fail. 
    */
    'webhook'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "webhook",
            "baseName": "webhook",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ItemImportRequestOptions.attributeTypeMap;
    }
}

