/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A JSON Web Key (JWK) that can be used in conjunction with [JWT libraries](https://jwt.io/#libraries-io) to verify Plaid webhooks
*/
export class JWKPublicKey extends null<String, any> {
    /**
    * The alg member identifies the cryptographic algorithm family used with the key.
    */
    'alg': string;
    /**
    * The crv member identifies the cryptographic curve used with the key.
    */
    'crv': string;
    /**
    * The kid (Key ID) member can be used to match a specific key. This can be used, for instance, to choose among a set of keys within the JWK during key rollover.
    */
    'kid': string;
    /**
    * The kty (key type) parameter identifies the cryptographic algorithm family used with the key, such as RSA or EC.
    */
    'kty': string;
    /**
    * The use (public key use) parameter identifies the intended use of the public key.
    */
    'use': string;
    /**
    * The x member contains the x coordinate for the elliptic curve point.
    */
    'x': string;
    /**
    * The y member contains the y coordinate for the elliptic curve point.
    */
    'y': string;
    /**
    * The timestamp when the key was created, in Unix time.
    */
    'createdAt': number;
    /**
    * The timestamp when the key expired, in Unix time.
    */
    'expiredAt': number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "alg",
            "baseName": "alg",
            "type": "string"
        },
        {
            "name": "crv",
            "baseName": "crv",
            "type": "string"
        },
        {
            "name": "kid",
            "baseName": "kid",
            "type": "string"
        },
        {
            "name": "kty",
            "baseName": "kty",
            "type": "string"
        },
        {
            "name": "use",
            "baseName": "use",
            "type": "string"
        },
        {
            "name": "x",
            "baseName": "x",
            "type": "string"
        },
        {
            "name": "y",
            "baseName": "y",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number"
        },
        {
            "name": "expiredAt",
            "baseName": "expired_at",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(JWKPublicKey.attributeTypeMap);
    }
}

