/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PlaidError } from './plaidError';

/**
* The webhook of type `LIABILITIES` and code `DEFAULT_UPDATE` will be fired when new or updated liabilities have been detected on a liabilities item.
*/
export class LiabilitiesDefaultUpdateWebhook {
    /**
    * `LIABILITIES`
    */
    'webhookType': string;
    /**
    * `DEFAULT_UPDATE`
    */
    'webhookCode': string;
    /**
    * The `item_id` of the Item associated with this webhook, warning, or error
    */
    'itemId': string;
    'error': PlaidError;
    /**
    * An array of `account_id`\'s for accounts that contain new liabilities.\'
    */
    'accountIdsWithNewLiabilities': Array<string>;
    /**
    * An object with keys of `account_id`\'s that are mapped to their respective liabilities fields that changed.  Example: `{ \"XMBvvyMGQ1UoLbKByoMqH3nXMj84ALSdE5B58\": [\"past_amount_due\"] }` 
    */
    'accountIdsWithUpdatedLiabilities': { [key: string]: Array<string>; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "webhookType",
            "baseName": "webhook_type",
            "type": "string"
        },
        {
            "name": "webhookCode",
            "baseName": "webhook_code",
            "type": "string"
        },
        {
            "name": "itemId",
            "baseName": "item_id",
            "type": "string"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "PlaidError"
        },
        {
            "name": "accountIdsWithNewLiabilities",
            "baseName": "account_ids_with_new_liabilities",
            "type": "Array<string>"
        },
        {
            "name": "accountIdsWithUpdatedLiabilities",
            "baseName": "account_ids_with_updated_liabilities",
            "type": "{ [key: string]: Array<string>; }"
        }    ];

    static getAttributeTypeMap() {
        return LiabilitiesDefaultUpdateWebhook.attributeTypeMap;
    }
}

