/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Address } from './address';
import { PSLFStatus } from './pSLFStatus';
import { StudentLoanRepaymentModel } from './studentLoanRepaymentModel';
import { StudentLoanStatus } from './studentLoanStatus';

/**
* Used to configure Sandbox test data for the Liabilities product
*/
export class LiabilityOverride extends null<String, any> {
    /**
    * The type of the liability object, either `credit` or `student`. Mortgages are not currently supported in the custom Sandbox.
    */
    'type': string;
    /**
    * The purchase APR percentage value. For simplicity, this is the only interest rate used to calculate interest charges. Can only be set if `type` is `credit`.
    */
    'purchaseApr': number;
    /**
    * The cash APR percentage value. Can only be set if `type` is `credit`.
    */
    'cashApr': number;
    /**
    * The balance transfer APR percentage value. Can only be set if `type` is `credit`. Can only be set if `type` is `credit`.
    */
    'balanceTransferApr': number;
    /**
    * The special APR percentage value. Can only be set if `type` is `credit`.
    */
    'specialApr': number;
    /**
    * Override the `last_payment_amount` field. Can only be set if `type` is `credit`.
    */
    'lastPaymentAmount': number;
    /**
    * Override the `minimum_payment_amount` field. Can only be set if `type` is `credit` or `student`.
    */
    'minimumPaymentAmount': number;
    /**
    * Override the `is_overdue` field
    */
    'isOverdue': boolean;
    /**
    * The date on which the loan was initially lent, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format. Can only be set if `type` is `student`.
    */
    'originationDate': string;
    /**
    * The original loan principal. Can only be set if `type` is `student`.
    */
    'principal': number;
    /**
    * The interest rate on the loan as a percentage. Can only be set if `type` is `student`.
    */
    'nominalApr': number;
    /**
    * If set, interest capitalization begins at the given number of months after loan origination. By default interest is never capitalized. Can only be set if `type` is `student`.
    */
    'interestCapitalizationGracePeriodMonths': number;
    'repaymentModel': StudentLoanRepaymentModel;
    /**
    * Override the `expected_payoff_date` field. Can only be set if `type` is `student`.
    */
    'expectedPayoffDate': string;
    /**
    * Override the `guarantor` field. Can only be set if `type` is `student`.
    */
    'guarantor': string;
    /**
    * Override the `is_federal` field. Can only be set if `type` is `student`.
    */
    'isFederal': boolean;
    /**
    * Override the `loan_name` field. Can only be set if `type` is `student`.
    */
    'loanName': string;
    'loanStatus': StudentLoanStatus;
    /**
    * Override the `payment_reference_number` field. Can only be set if `type` is `student`.
    */
    'paymentReferenceNumber': string;
    'pslfStatus': PSLFStatus;
    /**
    * Override the `repayment_plan.description` field. Can only be set if `type` is `student`.
    */
    'repaymentPlanDescription': string;
    /**
    * Override the `repayment_plan.type` field. Can only be set if `type` is `student`. Possible values are: `\"extended graduated\"`, `\"extended standard\"`, `\"graduated\"`, `\"income-contingent repayment\"`, `\"income-based repayment\"`, `\"interest only\"`, `\"other\"`, `\"pay as you earn\"`, `\"revised pay as you earn\"`, or `\"standard\"`.
    */
    'repaymentPlanType': string;
    /**
    * Override the `sequence_number` field. Can only be set if `type` is `student`.
    */
    'sequenceNumber': string;
    'servicerAddress': Address;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "purchaseApr",
            "baseName": "purchase_apr",
            "type": "number"
        },
        {
            "name": "cashApr",
            "baseName": "cash_apr",
            "type": "number"
        },
        {
            "name": "balanceTransferApr",
            "baseName": "balance_transfer_apr",
            "type": "number"
        },
        {
            "name": "specialApr",
            "baseName": "special_apr",
            "type": "number"
        },
        {
            "name": "lastPaymentAmount",
            "baseName": "last_payment_amount",
            "type": "number"
        },
        {
            "name": "minimumPaymentAmount",
            "baseName": "minimum_payment_amount",
            "type": "number"
        },
        {
            "name": "isOverdue",
            "baseName": "is_overdue",
            "type": "boolean"
        },
        {
            "name": "originationDate",
            "baseName": "origination_date",
            "type": "string"
        },
        {
            "name": "principal",
            "baseName": "principal",
            "type": "number"
        },
        {
            "name": "nominalApr",
            "baseName": "nominal_apr",
            "type": "number"
        },
        {
            "name": "interestCapitalizationGracePeriodMonths",
            "baseName": "interest_capitalization_grace_period_months",
            "type": "number"
        },
        {
            "name": "repaymentModel",
            "baseName": "repayment_model",
            "type": "StudentLoanRepaymentModel"
        },
        {
            "name": "expectedPayoffDate",
            "baseName": "expected_payoff_date",
            "type": "string"
        },
        {
            "name": "guarantor",
            "baseName": "guarantor",
            "type": "string"
        },
        {
            "name": "isFederal",
            "baseName": "is_federal",
            "type": "boolean"
        },
        {
            "name": "loanName",
            "baseName": "loan_name",
            "type": "string"
        },
        {
            "name": "loanStatus",
            "baseName": "loan_status",
            "type": "StudentLoanStatus"
        },
        {
            "name": "paymentReferenceNumber",
            "baseName": "payment_reference_number",
            "type": "string"
        },
        {
            "name": "pslfStatus",
            "baseName": "pslf_status",
            "type": "PSLFStatus"
        },
        {
            "name": "repaymentPlanDescription",
            "baseName": "repayment_plan_description",
            "type": "string"
        },
        {
            "name": "repaymentPlanType",
            "baseName": "repayment_plan_type",
            "type": "string"
        },
        {
            "name": "sequenceNumber",
            "baseName": "sequence_number",
            "type": "string"
        },
        {
            "name": "servicerAddress",
            "baseName": "servicer_address",
            "type": "Address"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(LiabilityOverride.attributeTypeMap);
    }
}

