/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Specifies options for initializing Link for use with the Deposit Switch (beta) product. This field is required if `deposit_switch` is included in the `products` array.
*/
export class LinkTokenCreateRequestDepositSwitch {
    /**
    * The `deposit_switch_id` provided by the `/deposit_switch/create` endpoint.
    */
    'depositSwitchId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "depositSwitchId",
            "baseName": "deposit_switch_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LinkTokenCreateRequestDepositSwitch.attributeTypeMap;
    }
}

