/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountFiltersResponse } from './accountFiltersResponse';
import { CountryCode } from './countryCode';
import { Products } from './products';

/**
* An object specifying the arguments originally provided to the `/link/token/create` call.
*/
export class LinkTokenGetMetadataResponse extends null<String, any> {
    /**
    * The `products` specified in the `/link/token/create` call.
    */
    'initialProducts': Array<Products>;
    /**
    * The `webhook` specified in the `/link/token/create` call.
    */
    'webhook': string | null;
    /**
    * The `country_codes` specified in the `/link/token/create` call.
    */
    'countryCodes': Array<CountryCode>;
    /**
    * The `language` specified in the `/link/token/create` call.
    */
    'language': string | null;
    'accountFilters'?: AccountFiltersResponse;
    /**
    * The `redirect_uri` specified in the `/link/token/create` call.
    */
    'redirectUri': string | null;
    /**
    * The `client_name` specified in the `/link/token/create` call.
    */
    'clientName': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "initialProducts",
            "baseName": "initial_products",
            "type": "Array<Products>"
        },
        {
            "name": "webhook",
            "baseName": "webhook",
            "type": "string"
        },
        {
            "name": "countryCodes",
            "baseName": "country_codes",
            "type": "Array<CountryCode>"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string"
        },
        {
            "name": "accountFilters",
            "baseName": "account_filters",
            "type": "AccountFiltersResponse"
        },
        {
            "name": "redirectUri",
            "baseName": "redirect_uri",
            "type": "string"
        },
        {
            "name": "clientName",
            "baseName": "client_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(LinkTokenGetMetadataResponse.attributeTypeMap);
    }
}

