/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Valid account subtypes for loan accounts. For a list containing descriptions of each subtype, see [Account schemas](https://plaid.com/docs/api/accounts/#StandaloneAccountType-loan).
*/
export enum LoanAccountSubtype {
    Auto = <any> 'auto',
    Business = <any> 'business',
    Commercial = <any> 'commercial',
    Construction = <any> 'construction',
    Consumer = <any> 'consumer',
    HomeEquity = <any> 'home equity',
    Loan = <any> 'loan',
    Mortgage = <any> 'mortgage',
    LineOfCredit = <any> 'line of credit',
    Student = <any> 'student',
    Other = <any> 'other',
    All = <any> 'all'
}
