/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Specifies the multi-factor authentication settings to use with this test account
*/
export class MFA extends null<String, any> {
    /**
    * Possible values are `device`, `selections`, or `questions`.  If value is `device`, the MFA answer is `1234`.  If value is `selections`, the MFA answer is always the first option.  If value is `questions`, the MFA answer is  `answer_<i>_<j>` for the j-th question in the i-th round, starting from 0. For example, the answer to the first question in the second round is `answer_1_0`.
    */
    'type': string;
    /**
    * Number of rounds of questions. Required if value of `type` is `questions`. 
    */
    'questionRounds': number;
    /**
    * Number of questions per round. Required if value of `type` is `questions`. If value of type is `selections`, default value is 2.
    */
    'questionsPerRound': number;
    /**
    * Number of rounds of selections, used if `type` is `selections`. Defaults to 1.
    */
    'selectionRounds': number;
    /**
    * Number of available answers per question, used if `type` is `selection`. Defaults to 2. 
    */
    'selectionsPerQuestion': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "questionRounds",
            "baseName": "question_rounds",
            "type": "number"
        },
        {
            "name": "questionsPerRound",
            "baseName": "questions_per_round",
            "type": "number"
        },
        {
            "name": "selectionRounds",
            "baseName": "selection_rounds",
            "type": "number"
        },
        {
            "name": "selectionsPerQuestion",
            "baseName": "selections_per_question",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(MFA.attributeTypeMap);
    }
}

