/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Object containing metadata about the interest rate for the mortgage.
*/
export class MortgageInterestRate extends null<String, any> {
    /**
    * Percentage value (interest rate of current mortgage, not APR) of interest payable on a loan.
    */
    'percentage': number | null;
    /**
    * The type of interest charged (fixed or variable).
    */
    'type': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(MortgageInterestRate.attributeTypeMap);
    }
}

