/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NumbersACH } from './numbersACH';

/**
* Identifying information for transferring money to or from a US account via ACH or wire transfer.
*/
export class NumbersACHNullable {
    /**
    * The Plaid account ID associated with the account numbers
    */
    'accountId': string;
    /**
    * The ACH account number for the account.  Note that when using OAuth with Chase Bank (`ins_56`), Chase will issue \"tokenized\" routing and account numbers, which are not the user\'s actual account and routing numbers. These tokenized numbers should work identically to normal account and routing numbers. The digits returned in the `mask` field will continue to reflect the actual account number, rather than the tokenized account number; for this reason, when displaying account numbers to the user to help them identify their account in your UI, always use the `mask` rather than truncating the `account` number. If a user revokes their permissions to your app, the tokenized numbers will continue to work for ACH deposits, but not withdrawals.
    */
    'account': string;
    /**
    * The ACH routing number for the account. If the institution is `ins_56`, this may be a tokenized routing number. For more information, see the description of the `account` field.
    */
    'routing': string;
    /**
    * The wire transfer routing number for the account, if available
    */
    'wireRouting': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        },
        {
            "name": "routing",
            "baseName": "routing",
            "type": "string"
        },
        {
            "name": "wireRouting",
            "baseName": "wire_routing",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NumbersACHNullable.attributeTypeMap;
    }
}

