/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Address } from './address';
import { Email } from './email';
import { PhoneNumber } from './phoneNumber';

/**
* Data about the owner or owners of an account. Any fields not specified will be filled in with default Sandbox information.
*/
export class OwnerOverride extends null<String, any> {
    /**
    * A list of names associated with the account by the financial institution. These should always be the names of individuals, even for business accounts. Note that the same name data will be used for all accounts associated with an Item.
    */
    'names': Array<string>;
    /**
    * A list of phone numbers associated with the account.
    */
    'phoneNumbers': Array<PhoneNumber>;
    /**
    * A list of email addresses associated with the account.
    */
    'emails': Array<Email>;
    /**
    * Data about the various addresses associated with the account.
    */
    'addresses': Array<Address>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "names",
            "baseName": "names",
            "type": "Array<string>"
        },
        {
            "name": "phoneNumbers",
            "baseName": "phone_numbers",
            "type": "Array<PhoneNumber>"
        },
        {
            "name": "emails",
            "baseName": "emails",
            "type": "Array<Email>"
        },
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<Address>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(OwnerOverride.attributeTypeMap);
    }
}

