/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentInitiationPayment } from './paymentInitiationPayment';

/**
* PaymentInitiationPaymentListResponse defines the response schema for `/payment_initiation/payment/list`
*/
export class PaymentInitiationPaymentListResponse extends null<String, any> {
    /**
    * An array of payments that have been created, associated with the given `client_id`.
    */
    'payments': Array<PaymentInitiationPayment>;
    /**
    * The value that, when used as the optional `cursor` parameter to `/payment_initiation/payment/list`, will return the next unreturned payment as its first payment.
    */
    'nextCursor': Date | null;
    /**
    * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    */
    'requestId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Array<PaymentInitiationPayment>"
        },
        {
            "name": "nextCursor",
            "baseName": "next_cursor",
            "type": "Date"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PaymentInitiationPaymentListResponse.attributeTypeMap);
    }
}

