/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentInitiationStandingOrderMetadata } from './paymentInitiationStandingOrderMetadata';

/**
* Metadata that captures what specific payment configurations an institution supports when making Payment Initiation requests.
*/
export class PaymentInitiationMetadata extends null<String, any> {
    /**
    * Indicates whether the institution supports payments from a different country.
    */
    'supportsInternationalPayments': boolean;
    /**
    * A mapping of currency to maximum payment amount (denominated in the smallest unit of currency) supported by the institution.  Example: `{\"GBP\": \"10000\"}` 
    */
    'maximumPaymentAmount': { [key: string]: string; };
    /**
    * Indicates whether the institution supports returning refund details when initiating a payment.
    */
    'supportsRefundDetails': boolean;
    'standingOrderMetadata': PaymentInitiationStandingOrderMetadata | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "supportsInternationalPayments",
            "baseName": "supports_international_payments",
            "type": "boolean"
        },
        {
            "name": "maximumPaymentAmount",
            "baseName": "maximum_payment_amount",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "supportsRefundDetails",
            "baseName": "supports_refund_details",
            "type": "boolean"
        },
        {
            "name": "standingOrderMetadata",
            "baseName": "standing_order_metadata",
            "type": "PaymentInitiationStandingOrderMetadata"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PaymentInitiationMetadata.attributeTypeMap);
    }
}

