/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExternalPaymentOptions } from './externalPaymentOptions';
import { ExternalPaymentScheduleRequest } from './externalPaymentScheduleRequest';
import { PaymentAmount } from './paymentAmount';

/**
* PaymentInitiationPaymentCreateRequest defines the request schema for `/payment_initiation/payment/create`
*/
export class PaymentInitiationPaymentCreateRequest {
    /**
    * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    */
    'clientId'?: string;
    /**
    * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    */
    'secret'?: string;
    /**
    * The ID of the recipient the payment is for.
    */
    'recipientId': string;
    /**
    * A reference for the payment. This must be an alphanumeric string with at most 18 characters and must not contain any special characters (since not all institutions support them).
    */
    'reference': string;
    'amount': PaymentAmount;
    'schedule'?: ExternalPaymentScheduleRequest;
    'options'?: ExternalPaymentOptions | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "recipientId",
            "baseName": "recipient_id",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "PaymentAmount"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "ExternalPaymentScheduleRequest"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "ExternalPaymentOptions"
        }    ];

    static getAttributeTypeMap() {
        return PaymentInitiationPaymentCreateRequest.attributeTypeMap;
    }
}

