/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentAmount } from './paymentAmount';

/**
* PaymentInitiationRefund defines a payment initiation refund
*/
export class PaymentInitiationRefund extends null<String, any> {
    /**
    * The ID of the refund. Like all Plaid identifiers, the `refund_id` is case sensitive.
    */
    'refundId': string;
    'amount': PaymentAmount;
    /**
    * The status of the refund.  `PROCESSING`: The refund is currently being processed. The refund will automatically exit this state when processing is complete.  `INITIATED`: The refund has been successfully initiated.  `EXECUTED`: Indicates that the refund has been successfully executed.  `FAILED`: The refund has failed to be executed. This error is retryable once the root cause is resolved.
    */
    'status': PaymentInitiationRefund.StatusEnum;
    /**
    * The date and time of the last time the `status` was updated, in IS0 8601 format
    */
    'lastStatusUpdate': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "refundId",
            "baseName": "refund_id",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "PaymentAmount"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PaymentInitiationRefund.StatusEnum"
        },
        {
            "name": "lastStatusUpdate",
            "baseName": "last_status_update",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PaymentInitiationRefund.attributeTypeMap);
    }
}

export namespace PaymentInitiationRefund {
    export enum StatusEnum {
        Processing = <any> 'PROCESSING',
        Initiated = <any> 'INITIATED',
        Executed = <any> 'EXECUTED',
        Failed = <any> 'FAILED'
    }
}
