/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* PaymentInitiationPaymentCreateResponse defines the response schema for `/payment_initiation/payment/create`
*/
export class PaymentInitiationPaymentCreateResponse extends null<String, any> {
    /**
    * A unique ID identifying the payment
    */
    'paymentId': string;
    /**
    * For a payment returned by this endpoint, there is only one possible value:  `PAYMENT_STATUS_INPUT_NEEDED`: The initial phase of the payment
    */
    'status': PaymentInitiationPaymentCreateResponse.StatusEnum;
    /**
    * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    */
    'requestId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentId",
            "baseName": "payment_id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PaymentInitiationPaymentCreateResponse.StatusEnum"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PaymentInitiationPaymentCreateResponse.attributeTypeMap);
    }
}

export namespace PaymentInitiationPaymentCreateResponse {
    export enum StatusEnum {
        PaymentStatusInputNeeded = <any> 'PAYMENT_STATUS_INPUT_NEEDED'
    }
}
