/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* PaymentInitiationPaymentTokenCreateResponse defines the response schema for `/payment_initiation/payment/token/create`
*/
export class PaymentInitiationPaymentTokenCreateResponse extends null<String, any> {
    /**
    * A `payment_token` that can be provided to Link initialization to enter the payment initiation flow
    */
    'paymentToken': string;
    /**
    * The date and time at which the token will expire, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format. A `payment_token` expires after 15 minutes.
    */
    'paymentTokenExpirationTime': Date;
    /**
    * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    */
    'requestId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentToken",
            "baseName": "payment_token",
            "type": "string"
        },
        {
            "name": "paymentTokenExpirationTime",
            "baseName": "payment_token_expiration_time",
            "type": "Date"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PaymentInitiationPaymentTokenCreateResponse.attributeTypeMap);
    }
}

