/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentInitiationAddress } from './paymentInitiationAddress';
import { PaymentInitiationRecipient } from './paymentInitiationRecipient';
import { PaymentInitiationRecipientGetResponseAllOf } from './paymentInitiationRecipientGetResponseAllOf';
import { RecipientBACSNullable } from './recipientBACSNullable';

/**
* PaymentInitiationRecipientGetResponse defines the response schema for `/payment_initiation/recipient/get`
*/
export class PaymentInitiationRecipientGetResponse extends null<String, any> {
    /**
    * The ID of the recipient.
    */
    'recipientId': string;
    /**
    * The name of the recipient.
    */
    'name': string;
    'address'?: PaymentInitiationAddress | null;
    /**
    * The International Bank Account Number (IBAN) for the recipient.
    */
    'iban'?: string | null;
    'bacs'?: RecipientBACSNullable | null;
    /**
    * The EMI (E-Money Institution) recipient that this recipient is associated with, if any. This EMI recipient is used as an intermediary account to enable Plaid to reconcile the settlement of funds for Payment Initiation requests.
    */
    'emiRecipientId'?: string | null;
    /**
    * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    */
    'requestId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recipientId",
            "baseName": "recipient_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "PaymentInitiationAddress"
        },
        {
            "name": "iban",
            "baseName": "iban",
            "type": "string"
        },
        {
            "name": "bacs",
            "baseName": "bacs",
            "type": "RecipientBACSNullable"
        },
        {
            "name": "emiRecipientId",
            "baseName": "emi_recipient_id",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PaymentInitiationRecipientGetResponse.attributeTypeMap);
    }
}

