/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentScheduleInterval } from './paymentScheduleInterval';

/**
* Metadata specifically related to valid Payment Initiation standing order configurations for the institution.
*/
export class PaymentInitiationStandingOrderMetadata extends null<String, any> {
    /**
    * Indicates whether the institution supports closed-ended standing orders by providing an end date.
    */
    'supportsStandingOrderEndDate': boolean;
    /**
    * This is only applicable to `MONTHLY` standing orders. Indicates whether the institution supports negative integers (-1 to -5) for setting up a `MONTHLY` standing order relative to the end of the month.
    */
    'supportsStandingOrderNegativeExecutionDays': boolean;
    /**
    * A list of the valid standing order intervals supported by the institution.
    */
    'validStandingOrderIntervals': Array<PaymentScheduleInterval>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "supportsStandingOrderEndDate",
            "baseName": "supports_standing_order_end_date",
            "type": "boolean"
        },
        {
            "name": "supportsStandingOrderNegativeExecutionDays",
            "baseName": "supports_standing_order_negative_execution_days",
            "type": "boolean"
        },
        {
            "name": "validStandingOrderIntervals",
            "baseName": "valid_standing_order_intervals",
            "type": "Array<PaymentScheduleInterval>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PaymentInitiationStandingOrderMetadata.attributeTypeMap);
    }
}

