/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DistributionBreakdown } from './distributionBreakdown';

/**
* Details about the pay period.
*/
export class PayPeriodDetails extends null<String, any> {
    /**
    * The amount of the paycheck.
    */
    'checkAmount'?: number | null;
    'distributionBreakdown'?: Array<DistributionBreakdown>;
    /**
    * The pay period end date, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format: \"yyyy-mm-dd\".
    */
    'endDate'?: string | null;
    /**
    * Total earnings before tax/deductions.
    */
    'grossEarnings'?: number | null;
    /**
    * The date on which the paystub was issued, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (\"yyyy-mm-dd\").
    */
    'payDate'?: string | null;
    /**
    * The frequency at which an individual is paid.
    */
    'payFrequency'?: PayPeriodDetails.PayFrequencyEnum;
    /**
    * The date on which the paystub was issued, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (\"yyyy-mm-dd\").
    */
    'payDay'?: string | null;
    /**
    * The pay period start date, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format: \"yyyy-mm-dd\".
    */
    'startDate'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "checkAmount",
            "baseName": "check_amount",
            "type": "number"
        },
        {
            "name": "distributionBreakdown",
            "baseName": "distribution_breakdown",
            "type": "Array<DistributionBreakdown>"
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string"
        },
        {
            "name": "grossEarnings",
            "baseName": "gross_earnings",
            "type": "number"
        },
        {
            "name": "payDate",
            "baseName": "pay_date",
            "type": "string"
        },
        {
            "name": "payFrequency",
            "baseName": "pay_frequency",
            "type": "PayPeriodDetails.PayFrequencyEnum"
        },
        {
            "name": "payDay",
            "baseName": "pay_day",
            "type": "string"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PayPeriodDetails.attributeTypeMap);
    }
}

export namespace PayPeriodDetails {
    export enum PayFrequencyEnum {
        PayFrequencyUnknown = <any> 'PAY_FREQUENCY_UNKNOWN',
        PayFrequencyWeekly = <any> 'PAY_FREQUENCY_WEEKLY',
        PayFrequencyBiweekly = <any> 'PAY_FREQUENCY_BIWEEKLY',
        PayFrequencySemimonthly = <any> 'PAY_FREQUENCY_SEMIMONTHLY',
        PayFrequencyMonthly = <any> 'PAY_FREQUENCY_MONTHLY',
        Null = <any> 'null'
    }
}
