/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The address of the employee.
*/
export class PaystubOverrideEmployeeAddress {
    /**
    * The full city name.
    */
    'city'?: string;
    /**
    * The region or state Example: `\"NC\"`
    */
    'region'?: string;
    /**
    * The full street address Example: `\"564 Main Street, APT 15\"`
    */
    'street'?: string;
    /**
    * 5 digit postal code.
    */
    'postalCode'?: string;
    /**
    * The country of the address.
    */
    'country'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "street",
            "baseName": "street",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postal_code",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaystubOverrideEmployeeAddress.attributeTypeMap;
    }
}

