/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The amount of income earned year to date, as based on paystub data.
*/
export class PaystubYTDDetails extends null<String, any> {
    /**
    * Year-to-date gross earnings.
    */
    'grossEarnings'?: number | null;
    /**
    * Year-to-date net (take home) earnings.
    */
    'netEarnings'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "grossEarnings",
            "baseName": "gross_earnings",
            "type": "number"
        },
        {
            "name": "netEarnings",
            "baseName": "net_earnings",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PaystubYTDDetails.attributeTypeMap);
    }
}

