/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The frequency at which the employee is paid. Possible values: `MONTHLY`, `BI-WEEKLY`, `WEEKLY`, `SEMI-MONTHLY`.
*/
export enum PaystubPayFrequency {
    Monthly = <any> 'MONTHLY',
    BiWeekly = <any> 'BI-WEEKLY',
    Weekly = <any> 'WEEKLY',
    SemiMonthly = <any> 'SEMI-MONTHLY',
    Null = <any> 'null'
}
