/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Address on the paystub
*/
export class PaystubAddress extends null<String, any> {
    /**
    * The full city name.
    */
    'city'?: string | null;
    /**
    * The ISO 3166-1 alpha-2 country code.
    */
    'country'?: string | null;
    /**
    * The postal code of the address.
    */
    'postalCode'?: string | null;
    /**
    * The region or state Example: `\"NC\"`
    */
    'region'?: string | null;
    /**
    * The full street address.
    */
    'street'?: string | null;
    /**
    * Street address line 1.
    */
    'line1'?: string | null;
    /**
    * Street address line 2.
    */
    'line2'?: string | null;
    /**
    * The region or state Example: `\"NC\"`
    */
    'stateCode'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postal_code",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "street",
            "baseName": "street",
            "type": "string"
        },
        {
            "name": "line1",
            "baseName": "line1",
            "type": "string"
        },
        {
            "name": "line2",
            "baseName": "line2",
            "type": "string"
        },
        {
            "name": "stateCode",
            "baseName": "state_code",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PaystubAddress.attributeTypeMap);
    }
}

