/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Fired when an Item’s access consent is expiring in 7 days. Some Items have explicit expiration times and we try to relay this when possible to reduce service disruption. This can be resolved by having the user go through Link’s update mode.
*/
export class PendingExpirationWebhook extends null<String, any> {
    /**
    * `ITEM`
    */
    'webhookType': string;
    /**
    * `PENDING_EXPIRATION`
    */
    'webhookCode': string;
    /**
    * The `item_id` of the Item associated with this webhook, warning, or error
    */
    'itemId': string;
    /**
    * The date and time at which the Item\'s access consent will expire, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format
    */
    'consentExpirationTime': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "webhookType",
            "baseName": "webhook_type",
            "type": "string"
        },
        {
            "name": "webhookCode",
            "baseName": "webhook_code",
            "type": "string"
        },
        {
            "name": "itemId",
            "baseName": "item_id",
            "type": "string"
        },
        {
            "name": "consentExpirationTime",
            "baseName": "consent_expiration_time",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PendingExpirationWebhook.attributeTypeMap);
    }
}

