/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Information describing the intent of the transaction. Most relevant for personal finance use cases, but not limited to such use cases. The field is currently in beta.  The complete category can be generated by concatenating primary and detailed categories.  This feature is currently in beta – to request access, contact transactions-feedback@plaid.com.
*/
export class PersonalFinanceCategory extends null<String, any> {
    /**
    * A high level category that communicates the broad category of the transaction.
    */
    'primary': string;
    /**
    * Provides additional granularity to the primary categorization.
    */
    'detailed': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "primary",
            "baseName": "primary",
            "type": "string"
        },
        {
            "name": "detailed",
            "baseName": "detailed",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PersonalFinanceCategory.attributeTypeMap);
    }
}

