/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A phone number
*/
export class PhoneNumber extends null<String, any> {
    /**
    * The phone number.
    */
    'data': string;
    /**
    * When `true`, identifies the phone number as the primary number on an account.
    */
    'primary': boolean;
    /**
    * The type of phone number.
    */
    'type': PhoneNumber.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "string"
        },
        {
            "name": "primary",
            "baseName": "primary",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PhoneNumber.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PhoneNumber.attributeTypeMap);
    }
}

export namespace PhoneNumber {
    export enum TypeEnum {
        Home = <any> 'home',
        Work = <any> 'work',
        Office = <any> 'office',
        Mobile = <any> 'mobile',
        Mobile1 = <any> 'mobile1',
        Other = <any> 'other'
    }
}
