/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NumbersACHNullable } from './numbersACHNullable';
import { NumbersBACSNullable } from './numbersBACSNullable';
import { NumbersEFTNullable } from './numbersEFTNullable';
import { NumbersInternationalNullable } from './numbersInternationalNullable';

/**
* An object containing identifying numbers used for making electronic transfers to and from the `account`. The identifying number type (ACH, EFT, IBAN, or BACS) used will depend on the country of the account. An account may have more than one number type. If a particular identifying number type is not used by the `account` for which auth data has been requested, a null value will be returned.
*/
export class ProcessorNumber extends null<String, any> {
    'ach'?: NumbersACHNullable | null;
    'eft'?: NumbersEFTNullable | null;
    'international'?: NumbersInternationalNullable | null;
    'bacs'?: NumbersBACSNullable | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ach",
            "baseName": "ach",
            "type": "NumbersACHNullable"
        },
        {
            "name": "eft",
            "baseName": "eft",
            "type": "NumbersEFTNullable"
        },
        {
            "name": "international",
            "baseName": "international",
            "type": "NumbersInternationalNullable"
        },
        {
            "name": "bacs",
            "baseName": "bacs",
            "type": "NumbersBACSNullable"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ProcessorNumber.attributeTypeMap);
    }
}

