/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A detailed breakdown of the institution\'s performance for a request type. The values for `success`, `error_plaid`, and `error_institution` sum to 1.
*/
export class ProductStatusBreakdown extends null<String, any> {
    /**
    * The percentage of login attempts that are successful, expressed as a decimal.
    */
    'success': number;
    /**
    * The percentage of logins that are failing due to an internal Plaid issue, expressed as a decimal. 
    */
    'errorPlaid': number;
    /**
    * The percentage of logins that are failing due to an issue in the institution\'s system, expressed as a decimal.
    */
    'errorInstitution': number;
    /**
    * The `refresh_interval` may be `DELAYED` or `STOPPED` even when the success rate is high. This value is only returned for Transactions status breakdowns.
    */
    'refreshInterval'?: ProductStatusBreakdown.RefreshIntervalEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "number"
        },
        {
            "name": "errorPlaid",
            "baseName": "error_plaid",
            "type": "number"
        },
        {
            "name": "errorInstitution",
            "baseName": "error_institution",
            "type": "number"
        },
        {
            "name": "refreshInterval",
            "baseName": "refresh_interval",
            "type": "ProductStatusBreakdown.RefreshIntervalEnum"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ProductStatusBreakdown.attributeTypeMap);
    }
}

export namespace ProductStatusBreakdown {
    export enum RefreshIntervalEnum {
        Normal = <any> 'NORMAL',
        Delayed = <any> 'DELAYED',
        Stopped = <any> 'STOPPED'
    }
}
