/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Information about the student\'s eligibility in the Public Service Loan Forgiveness program. This is only returned if the institution is Fedloan (`ins_116527`). 
*/
export class PSLFStatus extends null<String, any> {
    /**
    * The estimated date borrower will have completed 120 qualifying monthly payments. Returned in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    */
    'estimatedEligibilityDate': string | null;
    /**
    * The number of qualifying payments that have been made.
    */
    'paymentsMade': number | null;
    /**
    * The number of qualifying payments remaining.
    */
    'paymentsRemaining': number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "estimatedEligibilityDate",
            "baseName": "estimated_eligibility_date",
            "type": "string"
        },
        {
            "name": "paymentsMade",
            "baseName": "payments_made",
            "type": "number"
        },
        {
            "name": "paymentsRemaining",
            "baseName": "payments_remaining",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PSLFStatus.attributeTypeMap);
    }
}

