/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* SandboxItemFireWebhookRequest defines the request schema for `/sandbox/item/fire_webhook`
*/
export class SandboxItemFireWebhookRequest {
    /**
    * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    */
    'clientId'?: string;
    /**
    * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    */
    'secret'?: string;
    /**
    * The access token associated with the Item data is being requested for.
    */
    'accessToken': string;
    /**
    * The following values for `webhook_code` are supported:  * `DEFAULT_UPDATE` * `NEW_ACCOUNTS_AVAILABLE`
    */
    'webhookCode': SandboxItemFireWebhookRequest.WebhookCodeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string"
        },
        {
            "name": "webhookCode",
            "baseName": "webhook_code",
            "type": "SandboxItemFireWebhookRequest.WebhookCodeEnum"
        }    ];

    static getAttributeTypeMap() {
        return SandboxItemFireWebhookRequest.attributeTypeMap;
    }
}

export namespace SandboxItemFireWebhookRequest {
    export enum WebhookCodeEnum {
        DefaultUpdate = <any> 'DEFAULT_UPDATE',
        NewAccountsAvailable = <any> 'NEW_ACCOUNTS_AVAILABLE'
    }
}
