/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Specify the security associated with the holding or investment transaction. When inputting custom security data to the Sandbox, Plaid will perform post-data-retrieval normalization and enrichment. These processes may cause the data returned by the Sandbox to be slightly different from the data you input. An ISO-4217 currency code and a security identifier (`ticker_symbol`, `cusip`, `isin`, or `sedol`) are required.
*/
export class SecurityOverride {
    /**
    * 12-character ISIN, a globally unique securities identifier.
    */
    'isin'?: string;
    /**
    * 9-character CUSIP, an identifier assigned to North American securities.
    */
    'cusip'?: string;
    /**
    * 7-character SEDOL, an identifier assigned to securities in the UK.
    */
    'sedol'?: string;
    /**
    * A descriptive name for the security, suitable for display.
    */
    'name'?: string;
    /**
    * The security’s trading symbol for publicly traded securities, and otherwise a short identifier if available.
    */
    'tickerSymbol'?: string;
    /**
    * Either a valid `iso_currency_code` or `unofficial_currency_code`
    */
    'currency'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isin",
            "baseName": "isin",
            "type": "string"
        },
        {
            "name": "cusip",
            "baseName": "cusip",
            "type": "string"
        },
        {
            "name": "sedol",
            "baseName": "sedol",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "tickerSymbol",
            "baseName": "ticker_symbol",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SecurityOverride.attributeTypeMap;
    }
}

