/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BankInitiatedReturnRisk } from './bankInitiatedReturnRisk';
import { CustomerInitiatedReturnRisk } from './customerInitiatedReturnRisk';

/**
* Risk scoring details broken down by risk category.
*/
export class SignalScores extends null<String, any> {
    'customerInitiatedReturnRisk'?: CustomerInitiatedReturnRisk;
    'bankInitiatedReturnRisk'?: BankInitiatedReturnRisk;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "customerInitiatedReturnRisk",
            "baseName": "customer_initiated_return_risk",
            "type": "CustomerInitiatedReturnRisk"
        },
        {
            "name": "bankInitiatedReturnRisk",
            "baseName": "bank_initiated_return_risk",
            "type": "BankInitiatedReturnRisk"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(SignalScores.attributeTypeMap);
    }
}

