/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The core attributes object contains additional data that can be used to assess the ACH return risk. Examples of data include:  `days_since_first_plaid_connection`: The number of days since the first time the Item was connected to an application via Plaid `plaid_connections_count_7d`: The number of times the Item has been connected to applications via Plaid over the past 7 days `plaid_connections_count_30d`: The number of times the Item has been connected to applications via Plaid over the past 30 days `total_plaid_connections_count`: The number of times the Item has been connected to applications via Plaid `is_savings_or_money_market_account`: Indicates whether the ACH transaction funding account is a savings/money market account  For the full list and detailed documentation of core attributes available, or to request that core attributes not be returned, contact Sales or your Plaid account manager
*/
export class SignalEvaluateCoreAttributes {
    /**
    * We parse and analyze historical transaction metadata to identify the number of possible past returns due to unauthorized transactions over the past 7 days from the account that will be debited.
    */
    'unauthorizedTransactionsCount7d'?: number;
    /**
    * We parse and analyze historical transaction metadata to identify the number of possible past returns due to unauthorized transactions over the past 30 days from the account that will be debited.
    */
    'unauthorizedTransactionsCount30d'?: number;
    /**
    * We parse and analyze historical transaction metadata to identify the number of possible past returns due to unauthorized transactions over the past 60 days from the account that will be debited.
    */
    'unauthorizedTransactionsCount60d'?: number;
    /**
    * We parse and analyze historical transaction metadata to identify the number of possible past returns due to unauthorized transactions over the past 90 days from the account that will be debited.
    */
    'unauthorizedTransactionsCount90d'?: number;
    /**
    * We parse and analyze historical transaction metadata to identify the number of possible past returns due to non-sufficient funds/overdrafts over the past 7 days from the account that will be debited.
    */
    'nsfOverdraftTransactionsCount7d'?: number;
    /**
    * We parse and analyze historical transaction metadata to identify the number of possible past returns due to non-sufficient funds/overdrafts over the past 30 days from the account that will be debited.
    */
    'nsfOverdraftTransactionsCount30d'?: number;
    /**
    * We parse and analyze historical transaction metadata to identify the number of possible past returns due to non-sufficient funds/overdrafts over the past 60 days from the account that will be debited.
    */
    'nsfOverdraftTransactionsCount60d'?: number;
    /**
    * We parse and analyze historical transaction metadata to identify the number of possible past returns due to non-sufficient funds/overdrafts over the past 90 days from the account that will be debited.
    */
    'nsfOverdraftTransactionsCount90d'?: number;
    /**
    * The number of days since the first time the Item was connected to an application via Plaid
    */
    'daysSinceFirstPlaidConnection'?: number | null;
    /**
    * The number of times the Item has been connected to applications via Plaid over the past 7 days
    */
    'plaidConnectionsCount7d'?: number | null;
    /**
    * The number of times the Item has been connected to applications via Plaid over the past 30 days
    */
    'plaidConnectionsCount30d'?: number | null;
    /**
    * The total number of times the Item has been connected to applications via Plaid
    */
    'totalPlaidConnectionsCount'?: number | null;
    /**
    * Indicates if the ACH transaction funding account is a savings/money market account
    */
    'isSavingsOrMoneyMarketAccount'?: boolean;
    /**
    * The total credit (inflow) transaction amount over the past 10 days from the account that will be debited
    */
    'totalCreditTransactionsAmount10d'?: number;
    /**
    * The total debit (outflow) transaction amount over the past 10 days from the account that will be debited
    */
    'totalDebitTransactionsAmount10d'?: number;
    /**
    * The 50th percentile of all credit (inflow) transaction amounts over the past 28 days from the account that will be debited
    */
    'p50CreditTransactionsAmount28d'?: number | null;
    /**
    * The 50th percentile of all debit (outflow) transaction amounts over the past 28 days from the account that will be debited
    */
    'p50DebitTransactionsAmount28d'?: number | null;
    /**
    * The 95th percentile of all credit (inflow) transaction amounts over the past 28 days from the account that will be debited
    */
    'p95CreditTransactionsAmount28d'?: number | null;
    /**
    * The 95th percentile of all debit (outflow) transaction amounts over the past 28 days from the account that will be debited
    */
    'p95DebitTransactionsAmount28d'?: number | null;
    /**
    * The number of days within the past 90 days when the account that will be debited had a negative end-of-day available balance
    */
    'daysWithNegativeBalanceCount90d'?: number | null;
    /**
    * The 90th percentile of the end-of-day available balance over the past 30 days of the account that will be debited
    */
    'p90EodBalance30d'?: number | null;
    /**
    * The 90th percentile of the end-of-day available balance over the past 60 days of the account that will be debited
    */
    'p90EodBalance60d'?: number | null;
    /**
    * The 90th percentile of the end-of-day available balance over the past 90 days of the account that will be debited
    */
    'p90EodBalance90d'?: number | null;
    /**
    * The 10th percentile of the end-of-day available balance over the past 30 days of the account that will be debited
    */
    'p10EodBalance30d'?: number | null;
    /**
    * The 10th percentile of the end-of-day available balance over the past 60 days of the account that will be debited
    */
    'p10EodBalance60d'?: number | null;
    /**
    * The 10th percentile of the end-of-day available balance over the past 90 days of the account that will be debited
    */
    'p10EodBalance90d'?: number | null;
    /**
    * Available balance, as of the `balance_last_updated` time. The available balance is the current balance less any outstanding holds or debits that have not yet posted to the account.
    */
    'availableBalance'?: number | null;
    /**
    * Current balance, as of the `balance_last_updated` time. The current balance is the total amount of funds in the account.
    */
    'currentBalance'?: number | null;
    /**
    * Timestamp in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DDTHH:mm:ssZ) indicating the last time that the balance for the given account has been updated.
    */
    'balanceLastUpdated'?: Date | null;
    /**
    * The number of times the account\'s phone numbers on file have changed over the past 28 days
    */
    'phoneChangeCount28d'?: number | null;
    /**
    * The number of times the account\'s phone numbers on file have changed over the past 90 days
    */
    'phoneChangeCount90d'?: number | null;
    /**
    * The number of times the account\'s email addresses on file have changed over the past 28 days
    */
    'emailChangeCount28d'?: number | null;
    /**
    * The number of times the account\'s email addresses on file have changed over the past 90 days
    */
    'emailChangeCount90d'?: number | null;
    /**
    * The number of times the account\'s addresses on file have changed over the past 28 days
    */
    'addressChangeCount28d'?: number | null;
    /**
    * The number of times the account\'s addresses on file have changed over the past 90 days
    */
    'addressChangeCount90d'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unauthorizedTransactionsCount7d",
            "baseName": "unauthorized_transactions_count_7d",
            "type": "number"
        },
        {
            "name": "unauthorizedTransactionsCount30d",
            "baseName": "unauthorized_transactions_count_30d",
            "type": "number"
        },
        {
            "name": "unauthorizedTransactionsCount60d",
            "baseName": "unauthorized_transactions_count_60d",
            "type": "number"
        },
        {
            "name": "unauthorizedTransactionsCount90d",
            "baseName": "unauthorized_transactions_count_90d",
            "type": "number"
        },
        {
            "name": "nsfOverdraftTransactionsCount7d",
            "baseName": "nsf_overdraft_transactions_count_7d",
            "type": "number"
        },
        {
            "name": "nsfOverdraftTransactionsCount30d",
            "baseName": "nsf_overdraft_transactions_count_30d",
            "type": "number"
        },
        {
            "name": "nsfOverdraftTransactionsCount60d",
            "baseName": "nsf_overdraft_transactions_count_60d",
            "type": "number"
        },
        {
            "name": "nsfOverdraftTransactionsCount90d",
            "baseName": "nsf_overdraft_transactions_count_90d",
            "type": "number"
        },
        {
            "name": "daysSinceFirstPlaidConnection",
            "baseName": "days_since_first_plaid_connection",
            "type": "number"
        },
        {
            "name": "plaidConnectionsCount7d",
            "baseName": "plaid_connections_count_7d",
            "type": "number"
        },
        {
            "name": "plaidConnectionsCount30d",
            "baseName": "plaid_connections_count_30d",
            "type": "number"
        },
        {
            "name": "totalPlaidConnectionsCount",
            "baseName": "total_plaid_connections_count",
            "type": "number"
        },
        {
            "name": "isSavingsOrMoneyMarketAccount",
            "baseName": "is_savings_or_money_market_account",
            "type": "boolean"
        },
        {
            "name": "totalCreditTransactionsAmount10d",
            "baseName": "total_credit_transactions_amount_10d",
            "type": "number"
        },
        {
            "name": "totalDebitTransactionsAmount10d",
            "baseName": "total_debit_transactions_amount_10d",
            "type": "number"
        },
        {
            "name": "p50CreditTransactionsAmount28d",
            "baseName": "p50_credit_transactions_amount_28d",
            "type": "number"
        },
        {
            "name": "p50DebitTransactionsAmount28d",
            "baseName": "p50_debit_transactions_amount_28d",
            "type": "number"
        },
        {
            "name": "p95CreditTransactionsAmount28d",
            "baseName": "p95_credit_transactions_amount_28d",
            "type": "number"
        },
        {
            "name": "p95DebitTransactionsAmount28d",
            "baseName": "p95_debit_transactions_amount_28d",
            "type": "number"
        },
        {
            "name": "daysWithNegativeBalanceCount90d",
            "baseName": "days_with_negative_balance_count_90d",
            "type": "number"
        },
        {
            "name": "p90EodBalance30d",
            "baseName": "p90_eod_balance_30d",
            "type": "number"
        },
        {
            "name": "p90EodBalance60d",
            "baseName": "p90_eod_balance_60d",
            "type": "number"
        },
        {
            "name": "p90EodBalance90d",
            "baseName": "p90_eod_balance_90d",
            "type": "number"
        },
        {
            "name": "p10EodBalance30d",
            "baseName": "p10_eod_balance_30d",
            "type": "number"
        },
        {
            "name": "p10EodBalance60d",
            "baseName": "p10_eod_balance_60d",
            "type": "number"
        },
        {
            "name": "p10EodBalance90d",
            "baseName": "p10_eod_balance_90d",
            "type": "number"
        },
        {
            "name": "availableBalance",
            "baseName": "available_balance",
            "type": "number"
        },
        {
            "name": "currentBalance",
            "baseName": "current_balance",
            "type": "number"
        },
        {
            "name": "balanceLastUpdated",
            "baseName": "balance_last_updated",
            "type": "Date"
        },
        {
            "name": "phoneChangeCount28d",
            "baseName": "phone_change_count_28d",
            "type": "number"
        },
        {
            "name": "phoneChangeCount90d",
            "baseName": "phone_change_count_90d",
            "type": "number"
        },
        {
            "name": "emailChangeCount28d",
            "baseName": "email_change_count_28d",
            "type": "number"
        },
        {
            "name": "emailChangeCount90d",
            "baseName": "email_change_count_90d",
            "type": "number"
        },
        {
            "name": "addressChangeCount28d",
            "baseName": "address_change_count_28d",
            "type": "number"
        },
        {
            "name": "addressChangeCount90d",
            "baseName": "address_change_count_90d",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SignalEvaluateCoreAttributes.attributeTypeMap;
    }
}

