/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SignalAddressData } from './signalAddressData';
import { SignalPersonName } from './signalPersonName';

/**
* Details about the end user initiating the transaction (i.e., the account holder).
*/
export class SignalUser {
    'name'?: SignalPersonName | null;
    /**
    * The user\'s phone number, in E.164 format: +{countrycode}{number}. For example: \"+14151234567\"
    */
    'phoneNumber'?: string | null;
    /**
    * The user\'s email address.
    */
    'emailAddress'?: string | null;
    'address'?: SignalAddressData | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "SignalPersonName"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "emailAddress",
            "baseName": "email_address",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "SignalAddressData"
        }    ];

    static getAttributeTypeMap() {
        return SignalUser.attributeTypeMap;
    }
}

