/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The user\'s legal name
*/
export class SignalPersonName {
    /**
    * The user\'s name prefix (e.g. \"Mr.\")
    */
    'prefix'?: string | null;
    /**
    * The user\'s given name. If the user has a one-word name, it should be provided in this field.
    */
    'givenName'?: string | null;
    /**
    * The user\'s middle name
    */
    'middleName'?: string | null;
    /**
    * The user\'s family name / surname
    */
    'familyName'?: string | null;
    /**
    * The user\'s name suffix (e.g. \"II\")
    */
    'suffix'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "prefix",
            "baseName": "prefix",
            "type": "string"
        },
        {
            "name": "givenName",
            "baseName": "given_name",
            "type": "string"
        },
        {
            "name": "middleName",
            "baseName": "middle_name",
            "type": "string"
        },
        {
            "name": "familyName",
            "baseName": "family_name",
            "type": "string"
        },
        {
            "name": "suffix",
            "baseName": "suffix",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SignalPersonName.attributeTypeMap;
    }
}

