/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SignalDevice } from './signalDevice';
import { SignalUser } from './signalUser';

/**
* SignalEvaluateRequest defines the request schema for `/signal/evaluate`
*/
export class SignalEvaluateRequest {
    /**
    * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    */
    'clientId'?: string;
    /**
    * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    */
    'secret'?: string;
    /**
    * The access token associated with the Item data is being requested for.
    */
    'accessToken': string;
    /**
    * The `account_id` of the account whose verification status is to be modified
    */
    'accountId': string;
    /**
    * The unique ID that you would like to use to refer to this transaction. For your convenience mapping your internal data, you could use your internal ID/identifier for this transaction. The max length for this field is 36 characters.
    */
    'clientTransactionId': string;
    /**
    * The transaction amount, in USD (e.g. `102.05`)
    */
    'amount': number;
    /**
    * `true` if the end user is present while initiating the ACH transfer and the endpoint is being called; `false` otherwise (for example, when the ACH transfer is scheduled and the end user is not present, or you call this endpoint after the ACH transfer but before submitting the Nacha file for ACH processing).
    */
    'userPresent'?: boolean | null;
    /**
    * A unique ID that identifies the end user in your system. This ID is used to correlate requests by a user with multiple Items. The max length for this field is 36 characters.
    */
    'clientUserId'?: string;
    'user'?: SignalUser;
    'device'?: SignalDevice;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "clientTransactionId",
            "baseName": "client_transaction_id",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "userPresent",
            "baseName": "user_present",
            "type": "boolean"
        },
        {
            "name": "clientUserId",
            "baseName": "client_user_id",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "SignalUser"
        },
        {
            "name": "device",
            "baseName": "device",
            "type": "SignalDevice"
        }    ];

    static getAttributeTypeMap() {
        return SignalEvaluateRequest.attributeTypeMap;
    }
}

