/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An object representing the status of the student loan
*/
export class StudentLoanStatus extends null<String, any> {
    /**
    * The date until which the loan will be in its current status. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). 
    */
    'endDate': string | null;
    /**
    * The status type of the student loan
    */
    'type': StudentLoanStatus.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "StudentLoanStatus.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(StudentLoanStatus.attributeTypeMap);
    }
}

export namespace StudentLoanStatus {
    export enum TypeEnum {
        Cancelled = <any> 'cancelled',
        ChargedOff = <any> 'charged off',
        Claim = <any> 'claim',
        Consolidated = <any> 'consolidated',
        Deferment = <any> 'deferment',
        Delinquent = <any> 'delinquent',
        Discharged = <any> 'discharged',
        Extension = <any> 'extension',
        Forbearance = <any> 'forbearance',
        InGrace = <any> 'in grace',
        InMilitary = <any> 'in military',
        InSchool = <any> 'in school',
        NotFullyDisbursed = <any> 'not fully disbursed',
        Other = <any> 'other',
        PaidInFull = <any> 'paid in full',
        Refunded = <any> 'refunded',
        Repayment = <any> 'repayment',
        Transferred = <any> 'transferred'
    }
}
