/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An object representing the repayment plan for the student loan
*/
export class StudentRepaymentPlan extends null<String, any> {
    /**
    * The description of the repayment plan as provided by the servicer.
    */
    'description': string | null;
    /**
    * The type of the repayment plan.
    */
    'type': StudentRepaymentPlan.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "StudentRepaymentPlan.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(StudentRepaymentPlan.attributeTypeMap);
    }
}

export namespace StudentRepaymentPlan {
    export enum TypeEnum {
        ExtendedGraduated = <any> 'extended graduated',
        ExtendedStandard = <any> 'extended standard',
        Graduated = <any> 'graduated',
        IncomeContingentRepayment = <any> 'income-contingent repayment',
        IncomeBasedRepayment = <any> 'income-based repayment',
        InterestOnly = <any> 'interest-only',
        Other = <any> 'other',
        PayAsYouEarn = <any> 'pay as you earn',
        RevisedPayAsYouEarn = <any> 'revised pay as you earn',
        Standard = <any> 'standard',
        Null = <any> 'null'
    }
}
