/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { W2 } from './w2';

/**
* Data about an official document used to report the user\'s income to the IRS.
*/
export class Taxform extends null<String, any> {
    /**
    * An identifier of the document referenced by the document metadata.
    */
    'docId'?: string;
    /**
    * The type of tax document. Currently, the only supported value is `w2`.
    */
    'documentType': string;
    'w2'?: W2;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "docId",
            "baseName": "doc_id",
            "type": "string"
        },
        {
            "name": "documentType",
            "baseName": "document_type",
            "type": "string"
        },
        {
            "name": "w2",
            "baseName": "w2",
            "type": "W2"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Taxform.attributeTypeMap);
    }
}

