/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Pay } from './pay';
import { TotalCanonicalDescription } from './totalCanonicalDescription';

/**
* An object representing both the current pay period and year to date amount for a category.
*/
export class Total extends null<String, any> {
    'canonicalDescription'?: TotalCanonicalDescription | null;
    /**
    * Text of the line item as printed on the paystub.
    */
    'description'?: string | null;
    'currentPay'?: Pay;
    'ytdPay'?: Pay;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "canonicalDescription",
            "baseName": "canonical_description",
            "type": "TotalCanonicalDescription"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "currentPay",
            "baseName": "current_pay",
            "type": "Pay"
        },
        {
            "name": "ytdPay",
            "baseName": "ytd_pay",
            "type": "Pay"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Total.attributeTypeMap);
    }
}

