/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ACHClass } from './aCHClass';
import { TransferIntentCreateMode } from './transferIntentCreateMode';
import { TransferUserInRequest } from './transferUserInRequest';

/**
* Defines the request schema for `/transfer/intent/create`
*/
export class TransferIntentCreateRequest {
    /**
    * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    */
    'clientId': string;
    /**
    * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    */
    'secret': string;
    /**
    * The Plaid `account_id` for the account that will be debited or credited.
    */
    'accountId'?: string | null;
    'mode': TransferIntentCreateMode;
    /**
    * The amount of the transfer (decimal string with two digits of precision e.g. \"10.00\").
    */
    'amount': string;
    /**
    * A description for the underlying transfer. Maximum of 8 characters.
    */
    'description': string;
    'achClass': ACHClass;
    /**
    * Plaid’s unique identifier for the origination account for the intent. If not provided, the default account will be used.
    */
    'originationAccountId'?: string | null;
    'user': TransferUserInRequest;
    /**
    * The Metadata object is a mapping of client-provided string fields to any string value. The following limitations apply: - The JSON values must be Strings (no nested JSON objects allowed) - Only ASCII characters may be used - Maximum of 50 key/value pairs - Maximum key length of 40 characters - Maximum value length of 500 characters 
    */
    'metadata'?: { [key: string]: string; } | null;
    /**
    * The currency of the transfer amount, e.g. \"USD\"
    */
    'isoCurrencyCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "TransferIntentCreateMode"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "achClass",
            "baseName": "ach_class",
            "type": "ACHClass"
        },
        {
            "name": "originationAccountId",
            "baseName": "origination_account_id",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "TransferUserInRequest"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "isoCurrencyCode",
            "baseName": "iso_currency_code",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TransferIntentCreateRequest.attributeTypeMap;
    }
}

