/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransferEventType } from './transferEventType';
import { TransferFailure } from './transferFailure';
import { TransferType } from './transferType';

/**
* Represents an event in the Transfers API.
*/
export class TransferEvent extends null<String, any> {
    /**
    * Plaid’s unique identifier for this event. IDs are sequential unsigned 64-bit integers.
    */
    'eventId': number;
    /**
    * The datetime when this event occurred. This will be of the form `2006-01-02T15:04:05Z`.
    */
    'timestamp': Date;
    'eventType': TransferEventType;
    /**
    * The account ID associated with the transfer.
    */
    'accountId': string;
    /**
    * Plaid’s unique identifier for a transfer.
    */
    'transferId': string;
    /**
    * The ID of the origination account that this balance belongs to.
    */
    'originationAccountId': string | null;
    'transferType': TransferType;
    /**
    * The amount of the transfer (decimal string with two digits of precision e.g. \"10.00\").
    */
    'transferAmount': string;
    'failureReason': TransferFailure | null;
    /**
    * Plaid’s unique identifier for a sweep.
    */
    'sweepId': string | null;
    /**
    * A signed amount of how much was `swept` or `reverse_swept` (decimal string with two digits of precision e.g. \"-5.50\").
    */
    'sweepAmount': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eventId",
            "baseName": "event_id",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "TransferEventType"
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "transferId",
            "baseName": "transfer_id",
            "type": "string"
        },
        {
            "name": "originationAccountId",
            "baseName": "origination_account_id",
            "type": "string"
        },
        {
            "name": "transferType",
            "baseName": "transfer_type",
            "type": "TransferType"
        },
        {
            "name": "transferAmount",
            "baseName": "transfer_amount",
            "type": "string"
        },
        {
            "name": "failureReason",
            "baseName": "failure_reason",
            "type": "TransferFailure"
        },
        {
            "name": "sweepId",
            "baseName": "sweep_id",
            "type": "string"
        },
        {
            "name": "sweepAmount",
            "baseName": "sweep_amount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(TransferEvent.attributeTypeMap);
    }
}

