/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The direction of the flow of transfer funds.  - `PAYMENT` – Transfers funds from an end user\'s account to your business account.  - `DISBURSEMENT` – Transfers funds from your business account to an end user\'s account.
*/
export enum TransferIntentCreateMode {
    Payment = <any> 'PAYMENT',
    Disbursement = <any> 'DISBURSEMENT'
}
