/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RemovedTransaction } from './removedTransaction';
import { Transaction } from './transaction';

/**
* TransactionsSyncResponse defines the response schema for `/transactions/sync`
*/
export class TransactionsSyncResponse extends null<String, any> {
    /**
    * Transactions that have been added to the item since `cursor` ordered by ascending last modified time.
    */
    'added': Array<Transaction>;
    /**
    * Transactions that have been modified on the item since `cursor` ordered by ascending last modified time.
    */
    'modified': Array<Transaction>;
    /**
    * Transactions that have been removed from the item since `cursor` ordered by ascending last modified time.
    */
    'removed': Array<RemovedTransaction>;
    /**
    * Cursor used for fetching any future updates after the latest update provided in this response.
    */
    'nextCursor': string;
    /**
    * Represents if more than requested count of transaction updates exist. If true, the additional updates can be fetched by making an additional request with `cursor` set to `next_cursor`.
    */
    'hasMore': boolean;
    /**
    * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    */
    'requestId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "added",
            "baseName": "added",
            "type": "Array<Transaction>"
        },
        {
            "name": "modified",
            "baseName": "modified",
            "type": "Array<Transaction>"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "Array<RemovedTransaction>"
        },
        {
            "name": "nextCursor",
            "baseName": "next_cursor",
            "type": "string"
        },
        {
            "name": "hasMore",
            "baseName": "has_more",
            "type": "boolean"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(TransactionsSyncResponse.attributeTypeMap);
    }
}

