/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents a return on a Guaranteed ACH transfer that is included in the specified repayment.
*/
export class TransferRepaymentReturn extends null<String, any> {
    /**
    * The unique identifier of the guaranteed transfer that was returned.
    */
    'transferId': string;
    /**
    * The unique identifier of the corresponding `reversed` transfer event.
    */
    'eventId': number;
    /**
    * The value of the returned transfer.
    */
    'amount': string;
    /**
    * The currency of the repayment, e.g. \"USD\".
    */
    'isoCurrencyCode': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transferId",
            "baseName": "transfer_id",
            "type": "string"
        },
        {
            "name": "eventId",
            "baseName": "event_id",
            "type": "number"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "isoCurrencyCode",
            "baseName": "iso_currency_code",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(TransferRepaymentReturn.attributeTypeMap);
    }
}

