/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransferUserAddressInResponse } from './transferUserAddressInResponse';

/**
* The legal name and other information for the account holder.
*/
export class TransferUserInResponse extends null<String, any> {
    /**
    * The user\'s legal name.
    */
    'legalName': string;
    /**
    * The user\'s phone number.
    */
    'phoneNumber': string | null;
    /**
    * The user\'s email address.
    */
    'emailAddress': string | null;
    'address': TransferUserAddressInResponse | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "legalName",
            "baseName": "legal_name",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "emailAddress",
            "baseName": "email_address",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "TransferUserAddressInResponse"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(TransferUserInResponse.attributeTypeMap);
    }
}

