/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Employee } from './employee';
import { PaystubEmployer } from './paystubEmployer';
import { W2Box12 } from './w2Box12';
import { W2StateAndLocalWages } from './w2StateAndLocalWages';

/**
* W2 is an object that represents income data taken from a W2 tax document.
*/
export class W2 extends null<String, any> {
    'employer'?: PaystubEmployer;
    'employee'?: Employee;
    /**
    * The tax year of the W2 document.
    */
    'taxYear'?: string | null;
    /**
    * An employee identification number or EIN.
    */
    'employerIdNumber'?: string | null;
    /**
    * Wages from tips and other compensation.
    */
    'wagesTipsOtherComp'?: string | null;
    /**
    * Federal income tax withheld for the tax year.
    */
    'federalIncomeTaxWithheld'?: string | null;
    /**
    * Wages from social security.
    */
    'socialSecurityWages'?: string | null;
    /**
    * Social security tax withheld for the tax year.
    */
    'socialSecurityTaxWithheld'?: string | null;
    /**
    * Wages and tips from medicare.
    */
    'medicareWagesAndTips'?: string | null;
    /**
    * Medicare tax withheld for the tax year.
    */
    'medicareTaxWithheld'?: string | null;
    /**
    * Tips from social security.
    */
    'socialSecurityTips'?: string | null;
    /**
    * Allocated tips.
    */
    'allocatedTips'?: string | null;
    /**
    * Contents from box 9 on the W2.
    */
    'box9'?: string | null;
    /**
    * Dependent care benefits.
    */
    'dependentCareBenefits'?: string | null;
    /**
    * Nonqualified plans.
    */
    'nonqualifiedPlans'?: string | null;
    'box12'?: Array<W2Box12>;
    /**
    * Statutory employee.
    */
    'statutoryEmployee'?: string | null;
    /**
    * Retirement plan.
    */
    'retirementPlan'?: string | null;
    /**
    * Third party sick pay.
    */
    'thirdPartySickPay'?: string | null;
    /**
    * Other.
    */
    'other'?: string | null;
    'stateAndLocalWages'?: Array<W2StateAndLocalWages>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "employer",
            "baseName": "employer",
            "type": "PaystubEmployer"
        },
        {
            "name": "employee",
            "baseName": "employee",
            "type": "Employee"
        },
        {
            "name": "taxYear",
            "baseName": "tax_year",
            "type": "string"
        },
        {
            "name": "employerIdNumber",
            "baseName": "employer_id_number",
            "type": "string"
        },
        {
            "name": "wagesTipsOtherComp",
            "baseName": "wages_tips_other_comp",
            "type": "string"
        },
        {
            "name": "federalIncomeTaxWithheld",
            "baseName": "federal_income_tax_withheld",
            "type": "string"
        },
        {
            "name": "socialSecurityWages",
            "baseName": "social_security_wages",
            "type": "string"
        },
        {
            "name": "socialSecurityTaxWithheld",
            "baseName": "social_security_tax_withheld",
            "type": "string"
        },
        {
            "name": "medicareWagesAndTips",
            "baseName": "medicare_wages_and_tips",
            "type": "string"
        },
        {
            "name": "medicareTaxWithheld",
            "baseName": "medicare_tax_withheld",
            "type": "string"
        },
        {
            "name": "socialSecurityTips",
            "baseName": "social_security_tips",
            "type": "string"
        },
        {
            "name": "allocatedTips",
            "baseName": "allocated_tips",
            "type": "string"
        },
        {
            "name": "box9",
            "baseName": "box_9",
            "type": "string"
        },
        {
            "name": "dependentCareBenefits",
            "baseName": "dependent_care_benefits",
            "type": "string"
        },
        {
            "name": "nonqualifiedPlans",
            "baseName": "nonqualified_plans",
            "type": "string"
        },
        {
            "name": "box12",
            "baseName": "box_12",
            "type": "Array<W2Box12>"
        },
        {
            "name": "statutoryEmployee",
            "baseName": "statutory_employee",
            "type": "string"
        },
        {
            "name": "retirementPlan",
            "baseName": "retirement_plan",
            "type": "string"
        },
        {
            "name": "thirdPartySickPay",
            "baseName": "third_party_sick_pay",
            "type": "string"
        },
        {
            "name": "other",
            "baseName": "other",
            "type": "string"
        },
        {
            "name": "stateAndLocalWages",
            "baseName": "state_and_local_wages",
            "type": "Array<W2StateAndLocalWages>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(W2.attributeTypeMap);
    }
}

