/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WalletTransactionCounterpartyNumbers } from './walletTransactionCounterpartyNumbers';

/**
* An object representing the e-wallet transaction\'s counterparty
*/
export class WalletTransactionCounterparty extends null<String, any> {
    /**
    * The name of the counterparty
    */
    'name': string;
    'numbers': WalletTransactionCounterpartyNumbers;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "numbers",
            "baseName": "numbers",
            "type": "WalletTransactionCounterpartyNumbers"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WalletTransactionCounterparty.attributeTypeMap);
    }
}

