/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WalletTransactionAmount } from './walletTransactionAmount';
import { WalletTransactionCounterparty } from './walletTransactionCounterparty';

/**
* WalletTransactionExecuteRequest defines the request schema for `/wallet/transaction/execute`
*/
export class WalletTransactionExecuteRequest {
    /**
    * Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    */
    'clientId'?: string;
    /**
    * Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    */
    'secret'?: string;
    /**
    * A random key provided by the client, per unique wallet transaction. Maximum of 128 characters.  The API supports idempotency for safely retrying requests without accidentally performing the same operation twice. If a request to execute a wallet transaction fails due to a network connection error, then after a minimum delay of one minute, you can retry the request with the same idempotency key to guarantee that only a single wallet transaction is created. If the request was successfully processed, it will prevent any transaction that uses the same idempotency key, and was received within 24 hours of the first request, from being processed.
    */
    'idempotencyKey': string;
    /**
    * The ID of the e-wallet to debit from
    */
    'walletId': string;
    'counterparty': WalletTransactionCounterparty;
    'amount': WalletTransactionAmount;
    /**
    * A reference for the transaction. This must be an alphanumeric string with at most 18 characters and must not contain any special characters or spaces.
    */
    'reference': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "idempotencyKey",
            "baseName": "idempotency_key",
            "type": "string"
        },
        {
            "name": "walletId",
            "baseName": "wallet_id",
            "type": "string"
        },
        {
            "name": "counterparty",
            "baseName": "counterparty",
            "type": "WalletTransactionCounterparty"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "WalletTransactionAmount"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WalletTransactionExecuteRequest.attributeTypeMap;
    }
}

