/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The amount and currency of a transaction
*/
export class WalletTransactionAmount extends null<String, any> {
    /**
    * The ISO-4217 currency code of the transaction. Currently, only `\"GBP\"` is supported.
    */
    'isoCurrencyCode': WalletTransactionAmount.IsoCurrencyCodeEnum;
    /**
    * The amount of the transaction. Must contain at most two digits of precision e.g. `1.23`.
    */
    'value': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isoCurrencyCode",
            "baseName": "iso_currency_code",
            "type": "WalletTransactionAmount.IsoCurrencyCodeEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WalletTransactionAmount.attributeTypeMap);
    }
}

export namespace WalletTransactionAmount {
    export enum IsoCurrencyCodeEnum {
        Gbp = <any> 'GBP'
    }
}
