/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WalletTransactionAmount } from './walletTransactionAmount';
import { WalletTransactionCounterparty } from './walletTransactionCounterparty';
import { WalletTransactionStatus } from './walletTransactionStatus';

/**
* The transaction details
*/
export class WalletTransaction extends null<String, any> {
    /**
    * A unique ID identifying the transaction
    */
    'transactionId': string;
    /**
    * A reference for the transaction
    */
    'reference': string;
    /**
    * The type of of the transaction. Currently, only `\"PAYOUT\"` is supported.
    */
    'type': WalletTransaction.TypeEnum;
    'amount': WalletTransactionAmount;
    'counterparty': WalletTransactionCounterparty;
    'status': WalletTransactionStatus;
    /**
    * Timestamp when the transaction was created, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transactionId",
            "baseName": "transaction_id",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "WalletTransaction.TypeEnum"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "WalletTransactionAmount"
        },
        {
            "name": "counterparty",
            "baseName": "counterparty",
            "type": "WalletTransactionCounterparty"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "WalletTransactionStatus"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WalletTransaction.attributeTypeMap);
    }
}

export namespace WalletTransaction {
    export enum TypeEnum {
        Payout = <any> 'PAYOUT'
    }
}
