/**
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PlaidError } from './plaidError';

/**
* Fired when an Item\'s webhook is updated. This will be sent to the newly specified webhook.
*/
export class WebhookUpdateAcknowledgedWebhook extends null<String, any> {
    /**
    * `ITEM`
    */
    'webhookType': string;
    /**
    * `WEBHOOK_UPDATE_ACKNOWLEDGED`
    */
    'webhookCode': string;
    /**
    * The `item_id` of the Item associated with this webhook, warning, or error
    */
    'itemId': string;
    /**
    * The new webhook URL
    */
    'newWebhookUrl': string;
    'error'?: PlaidError;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "webhookType",
            "baseName": "webhook_type",
            "type": "string"
        },
        {
            "name": "webhookCode",
            "baseName": "webhook_code",
            "type": "string"
        },
        {
            "name": "itemId",
            "baseName": "item_id",
            "type": "string"
        },
        {
            "name": "newWebhookUrl",
            "baseName": "new_webhook_url",
            "type": "string"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "PlaidError"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WebhookUpdateAcknowledgedWebhook.attributeTypeMap);
    }
}

